/* GENERATED by engine/idlgen.mjs from canonical Web IDL (@webref/idl) — DO NOT EDIT.
 * Per-interface member SHAPE (name, kind, readonly, operation arity) straight from the spec. The binding
 * driver (idl_bind) installs these, resolving each member's BEHAVIOR from the component by name. */
#ifndef ENGINE_HOST_BROWSER_BINDINGS_IDL_GENERATED_H
#define ENGINE_HOST_BROWSER_BINDINGS_IDL_GENERATED_H
#include "bindings/idl.h"

static const IdlGenMember AbortSignal_IDL[] = {
  { "addEventListener", IDL_GEN_OP, 0, 2 },
  { "removeEventListener", IDL_GEN_OP, 0, 2 },
  { "dispatchEvent", IDL_GEN_OP, 0, 1 },
  { "when", IDL_GEN_OP, 0, 1 },
  { "aborted", IDL_GEN_ATTR, 1, 0 },
  { "reason", IDL_GEN_ATTR, 1, 0 },
  { "throwIfAborted", IDL_GEN_OP, 0, 0 },
  { "onabort", IDL_GEN_ATTR, 0, 0 },
};
#define AbortSignal_IDL_N 8

static const IdlGenMember AbortController_IDL[] = {
  { "signal", IDL_GEN_ATTR, 1, 0 },
  { "abort", IDL_GEN_OP, 0, 0 },
};
#define AbortController_IDL_N 2

#endif
