/* IDNA — WHATWG URL §3.3 "IDNA"'s domain parser ("domain to ASCII"), which is Unicode UTS-46 over RFC 3492's Punycode.
 *
 * WHY IT IS HERE. The URL parser reached a DFAIL naming this on the canonical corpus: five wpt files —
 * url-constructor, url-setters, url-origin and both IdnaTestV2 variants — stopped at the first non-ASCII
 * domain, which hid roughly seven hundred cases behind one missing capability. A domain is not a string the
 * parser may lowercase and hope: `münchen.de` IS `xn--mnchen-3ya.de` in the record, and every comparison a page
 * makes against `location.host` is against the A-label.
 *
 * PUNYCODE IS EXACT. RFC 3492 is a closed algorithm with no tables, so both directions are implemented to the
 * letter, including the overflow checks that make a hostile label a failure rather than a wrap.
 *
 * THE UTS-46 MAPPING IS UNICODE'S OWN TABLE, generated by engine/idnagen.mjs and committed as idna_table.h.
 * It stood here as full case folding plus NFC, which is most of the table's content and none of its DISALLOWED
 * set — so a code point UTS-46 refuses was accepted, and IdnaTestV2 reported that as 1126 `new URL(...)` calls
 * expecting a throw that never came. The generator applies WHATWG's configuration (UseSTD3ASCIIRules=false,
 * Transitional=false) once, so this file acts on four outcomes and re-derives none of it. */
#include <stdlib.h>
#include <string.h>

#include "check.h"
#include "cutils.h"
#include "libunicode.h"
#include "core/url/idna.h"
#include "core/url/idna_table.h"

/* ---- RFC 3492 ------------------------------------------------------------------------------------------- */

#define PUNY_BASE         36
#define PUNY_TMIN         1
#define PUNY_TMAX         26
#define PUNY_SKEW         38
#define PUNY_DAMP         700
#define PUNY_INITIAL_BIAS 72
#define PUNY_INITIAL_N    128
#define PUNY_MAXINT       0x7fffffff

static uint32_t puny_adapt(uint32_t delta, uint32_t numpoints, int firsttime)
{
    uint32_t k;
    delta = firsttime ? delta / PUNY_DAMP : delta >> 1;
    delta += delta / numpoints;
    for (k = 0; delta > ((PUNY_BASE - PUNY_TMIN) * PUNY_TMAX) / 2; k += PUNY_BASE)
        delta /= PUNY_BASE - PUNY_TMIN;
    return k + (PUNY_BASE - PUNY_TMIN + 1) * delta / (delta + PUNY_SKEW);
}

/* a-z0-9 as the digit alphabet; the encoder emits lowercase, which is what UTS-46 wants anyway. */
static int puny_digit(uint32_t cp)
{
    if (cp >= '0' && cp <= '9') return (int)(cp - '0' + 26);
    if (cp >= 'a' && cp <= 'z') return (int)(cp - 'a');
    if (cp >= 'A' && cp <= 'Z') return (int)(cp - 'A');
    return -1;
}

static char puny_char(int d) { return (char)(d < 26 ? 'a' + d : '0' + d - 26); }

/* Decode one label's Punycode body (everything after `xn--`) into code points. Returns the count, or -1. */
int idna_punycode_decode(const char *in, size_t in_len, uint32_t *out, int out_cap)
{
    uint32_t n = PUNY_INITIAL_N, i = 0, bias = PUNY_INITIAL_BIAS, oldi, w, k, t, digit;
    size_t b, j, ip = 0;
    int out_n = 0;

    /* the basic code points are everything before the LAST delimiter; with none, the whole input is extended */
    b = 0;
    for (j = 0; j < in_len; j++) if (in[j] == '-') b = j + 1;
    for (j = 0; j + 1 <= b && b > 0 && j < b - 1 + 1; j++) {
        if (j >= b - 1 + 1) break;
        if (j == b - 1) break;               /* the delimiter itself is not copied */
        if ((unsigned char)in[j] >= 0x80) return -1;
        if (out_n >= out_cap) return -1;
        out[out_n++] = (unsigned char)in[j];
    }
    ip = b;

    while (ip < in_len) {
        oldi = i;
        w = 1;
        for (k = PUNY_BASE;; k += PUNY_BASE) {
            int d;
            if (ip >= in_len) return -1;
            d = puny_digit((unsigned char)in[ip++]);
            if (d < 0) return -1;
            digit = (uint32_t)d;
            if (digit > (uint32_t)(PUNY_MAXINT - (int)i) / w) return -1;   /* overflow */
            i += digit * w;
            t = k <= bias ? PUNY_TMIN : (k >= bias + PUNY_TMAX ? PUNY_TMAX : k - bias);
            if (digit < t) break;
            if (w > (uint32_t)PUNY_MAXINT / (PUNY_BASE - t)) return -1;
            w *= PUNY_BASE - t;
        }
        bias = puny_adapt(i - oldi, (uint32_t)out_n + 1, oldi == 0);
        if (i / (uint32_t)(out_n + 1) > (uint32_t)(PUNY_MAXINT - (int)n)) return -1;
        n += i / (uint32_t)(out_n + 1);
        i %= (uint32_t)(out_n + 1);
        if (n > 0x10ffff || (n >= 0xd800 && n <= 0xdfff)) return -1;
        if (out_n >= out_cap) return -1;
        memmove(out + i + 1, out + i, (size_t)((uint32_t)out_n - i) * sizeof(uint32_t));
        out[i++] = n;
        out_n++;
    }
    return out_n;
}

/* Encode one label's code points as Punycode (WITHOUT the `xn--` prefix). Returns the byte length, or -1. */
int idna_punycode_encode(const uint32_t *in, int in_len, char *out, int out_cap)
{
    uint32_t n = PUNY_INITIAL_N, delta = 0, bias = PUNY_INITIAL_BIAS, m, q, k, t;
    int h, b, i, out_n = 0;

    for (i = 0; i < in_len; i++) {
        if (in[i] < 0x80) {
            if (out_n >= out_cap) return -1;
            out[out_n++] = (char)in[i];
        }
    }
    h = b = out_n;
    if (b > 0) {
        if (out_n >= out_cap) return -1;
        out[out_n++] = '-';
    }
    while (h < in_len) {
        m = 0x7fffffff;
        for (i = 0; i < in_len; i++) if (in[i] >= n && in[i] < m) m = in[i];
        if (m - n > (uint32_t)(PUNY_MAXINT - (int)delta) / (uint32_t)(h + 1)) return -1;
        delta += (m - n) * (uint32_t)(h + 1);
        n = m;
        for (i = 0; i < in_len; i++) {
            if (in[i] < n) {
                if (++delta == 0) return -1;
                continue;
            }
            if (in[i] != n) continue;
            for (q = delta, k = PUNY_BASE;; k += PUNY_BASE) {
                t = k <= bias ? PUNY_TMIN : (k >= bias + PUNY_TMAX ? PUNY_TMAX : k - bias);
                if (q < t) break;
                if (out_n >= out_cap) return -1;
                out[out_n++] = puny_char((int)(t + (q - t) % (PUNY_BASE - t)));
                q = (q - t) / (PUNY_BASE - t);
            }
            if (out_n >= out_cap) return -1;
            out[out_n++] = puny_char((int)q);
            bias = puny_adapt(delta, (uint32_t)(h + 1), h == b);
            delta = 0;
            h++;
        }
        delta++;
        n++;
    }
    return out_n;
}

/* ---- UTS-46 ---------------------------------------------------------------------------------------------- */

/* libunicode allocates through a caller-supplied reallocator so it never assumes an allocator; this component
   has no arena of its own, so it hands it plain realloc. */
static void *idna_cr_realloc(void *opaque, void *ptr, size_t size)
{
    (void)opaque;
    return realloc(ptr, size);
}

static void *idna_realloc(void *opaque, void *ptr, size_t size)
{
    (void)opaque;
    return realloc(ptr, size);
}

/* EXPAND UTF-8 INTO CODE POINTS — which is not a DECODE, and the difference is why this is here rather than in
   core/encoding. §3.5's host parser is what calls domain-to-ASCII, and its step 5 has already run UTF-8 decode
   without BOM on the percent-decoding, so what arrives is a SCALAR VALUE STRING: well-formed UTF-8, with a
   malformed sequence already turned into U+FFFD (which the mapping table then refuses, exactly as the
   standard's own note says). This walk therefore has no error handling left to do. It used to answer -1 for a
   malformed byte, and that answer is what let an OVERLONG form through as the character it spelled: 0xC1 0xA1
   passed the `(c & 0xe0) == 0xc0` test and came out as U+0061. There is one caller and it can no longer hand
   that over, so each impossible byte is a DFAIL at the byte rather than a return the caller must interpret. */
static int utf8_to_cps(const char *s, size_t n, uint32_t **out)
{
    uint32_t *cps = malloc(sizeof(uint32_t) * (n + 1));
    size_t i = 0;
    int m = 0;

    CHECK(cps, "idna: OOM decoding a domain");
    while (i < n) {
        unsigned char c = (unsigned char)s[i];
        uint32_t cp;
        int extra;
        if (c < 0x80)            { cp = c;          extra = 0; }
        else if ((c & 0xe0) == 0xc0) { cp = c & 0x1f; extra = 1; }
        else if ((c & 0xf0) == 0xe0) { cp = c & 0x0f; extra = 2; }
        else if ((c & 0xf8) == 0xf0) { cp = c & 0x07; extra = 3; }
        else {
            DFAIL("domain-to-ASCII was handed a byte that begins no UTF-8 sequence — §3.5 step 5's UTF-8 "
                  "decode without BOM did not run on this domain, so the caller is not the host parser or "
                  "the host parser skipped it");
            free(cps);
            return -1;
        }
        i++;
        while (extra--) {
            if (i >= n || ((unsigned char)s[i] & 0xc0) != 0x80) {
                DFAIL("domain-to-ASCII was handed a UTF-8 sequence that ends early or continues with a byte "
                      "that is not a continuation — the decode that guarantees a scalar value string did not "
                      "run on this domain");
                free(cps);
                return -1;
            }
            cp = (cp << 6) | ((unsigned char)s[i++] & 0x3f);
        }
        if (cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) {
            DFAIL("domain-to-ASCII was handed a surrogate or an out-of-range code point spelled in UTF-8 — "
                  "the decoder rejects both, so these bytes never went through it");
            free(cps);
            return -1;
        }
        cps[m++] = cp;
    }
    *out = cps;
    return m;
}

static void cps_to_utf8(const uint32_t *cps, int n, char *out, int *out_n)
{
    int i, k = 0;
    for (i = 0; i < n; i++) {
        uint32_t cp = cps[i];
        if (cp < 0x80) out[k++] = (char)cp;
        else if (cp < 0x800) { out[k++] = (char)(0xc0 | (cp >> 6)); out[k++] = (char)(0x80 | (cp & 0x3f)); }
        else if (cp < 0x10000) {
            out[k++] = (char)(0xe0 | (cp >> 12));
            out[k++] = (char)(0x80 | ((cp >> 6) & 0x3f));
            out[k++] = (char)(0x80 | (cp & 0x3f));
        } else {
            out[k++] = (char)(0xf0 | (cp >> 18));
            out[k++] = (char)(0x80 | ((cp >> 12) & 0x3f));
            out[k++] = (char)(0x80 | ((cp >> 6) & 0x3f));
            out[k++] = (char)(0x80 | (cp & 0x3f));
        }
    }
    *out_n = k;
}

/* UTS-46 step 1's MAPPING, from Unicode's own table. Case folding plus NFC stood here and was most of the
   table's content but not the DISALLOWED set, which is not decidable without it — so a code point UTS-46
   refuses was accepted, and IdnaTestV2 measured that as 1126 `new URL(...)` calls expecting a throw that never
   came. The generated table decides all four outcomes; the folding approximation is deleted rather than kept
   as a fallback for the code points the table also covers.
   Returns the mapped length, or -1 when a DISALLOWED code point makes the domain a failure. */
static int idna_range_of(uint32_t cp)
{
    int lo = 0, hi = (int)(sizeof(IDNA_RANGES) / sizeof(IDNA_RANGES[0])) - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (cp < IDNA_RANGES[mid].lo) hi = mid - 1;
        else if (cp > IDNA_RANGES[mid].hi) lo = mid + 1;
        else return mid;
    }
    return -1;
}

static int map_uts46(const uint32_t *in, int n, uint32_t **out)
{
    /* the longest mapping in the table is a handful of code points; four per input is ample and is asserted */
    uint32_t *o = malloc(sizeof(uint32_t) * (size_t)(n * 8 + 1));
    int i, m = 0;

    CHECK(o, "idna: OOM mapping a domain");
    for (i = 0; i < n; i++) {
        int r = idna_range_of(in[i]);
        const IdnaRange *e;
        /* A code point in NO range is one the table does not name, which UTS-46 treats as disallowed — an
           unassigned code point is not a domain character. */
        if (r < 0) { free(o); return -1; }
        e = &IDNA_RANGES[r];
        if (e->outcome == IDNA_ERROR) { free(o); return -1; }
        if (e->outcome == IDNA_REMOVE) continue;
        if (e->outcome == IDNA_KEEP) { o[m++] = in[i]; continue; }
        DCHECK(e->outcome == IDNA_MAP, "the IDNA table carried an outcome this mapper does not act on");
        DCHECK(e->len <= 8, "an IDNA mapping is longer than the allocation this mapper sized for");
        {
            int j;
            for (j = 0; j < e->len; j++) o[m++] = IDNA_MAP_POOL[e->off + j];
        }
    }
    *out = o;
    return m;
}

/* UTS-46 step 4.1's VALIDITY CRITERIA, for the one label kind that never went through the mapping: an `xn--`
   label passes the mapper as plain ASCII, so nothing has checked what it DECODES to. Without this, an A-label
   is a way to smuggle any code point at all into a domain — which is what 408 of IdnaTestV2's cases are, each
   an input expecting `new URL()` to throw.
   The criteria this checks are the ones WHATWG's configuration leaves on and the pinned corpus exercises:
   every code point must be VALID (the table's KEEP — a mapped or ignored one is not valid in an A-label), the
   label must carry no U+002E, and it must not BEGIN WITH A COMBINING MARK. CheckHyphens is false for WHATWG,
   so the 3rd/4th-position and leading/trailing hyphen rules are deliberately not here. */
static int idna_is_combining_mark(uint32_t cp)
{
    /* Built once: the general category M as a range set, from libunicode's own tables. */
    static CharRange marks;
    static int built;
    int i;
    if (!built) {
        cr_init(&marks, NULL, idna_cr_realloc);
        if (unicode_general_category(&marks, "M") < 0)
            DFAIL("libunicode does not know the general category M — the leading-combining-mark rule cannot "
                  "be decided without it");
        built = 1;
    }
    /* the ranges are [start, end) pairs in ascending order */
    for (i = 0; i + 1 < marks.len; i += 2)
        if (cp >= marks.points[i] && cp < marks.points[i + 1]) return 1;
    return 0;
}

#define IDNA_IN(set, cp) idna_in_ranges((set), (int)(sizeof(set) / sizeof((set)[0])), (cp))
static int idna_in_ranges(const uint32_t (*rs)[2], int n, uint32_t cp)
{
    int lo = 0, hi = n - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (cp < rs[mid][0]) hi = mid - 1;
        else if (cp > rs[mid][1]) lo = mid + 1;
        else return 1;
    }
    return 0;
}

/* RFC 5892 A.1 (ZERO WIDTH NON-JOINER) and A.2 (ZERO WIDTH JOINER) — UTS-46's CheckJoiners, which WHATWG
   turns ON. A joiner is not a character a domain may simply contain: it is valid only after a VIRAMA, and the
   non-joiner is additionally valid inside a cursive run, which is what A.1's regex
   `(L|D)(T)* ZWNJ (T)*(R|D)` says. Without these the two joiners passed as ordinary code points, which is 97
   of IdnaTestV2's inputs, each expecting `new URL()` to throw. */
static int idna_joiner_ok(const uint32_t *cps, int n, int i)
{
    int j;
    if (i > 0 && IDNA_IN(IDNA_VIRAMA, cps[i - 1])) return 1;
    if (cps[i] == 0x200d) return 0;            /* A.2 has no second clause */
    /* A.1's regex, read outwards from the joiner. */
    for (j = i - 1; j >= 0 && IDNA_IN(IDNA_JT_T, cps[j]); j--) ;
    if (j < 0 || !IDNA_IN(IDNA_JT_LD, cps[j])) return 0;
    for (j = i + 1; j < n && IDNA_IN(IDNA_JT_T, cps[j]); j++) ;
    if (j >= n || !IDNA_IN(IDNA_JT_RD, cps[j])) return 0;
    return 1;
}

static int idna_label_is_valid(const uint32_t *cps, int n)
{
    int i;
    if (n <= 0) return 1;            /* an empty label is the spec's business, not this check's */
    if (idna_is_combining_mark(cps[0])) return 0;
    for (i = 0; i < n; i++) {
        int r;
        if (cps[i] == '.') return 0;
        if (cps[i] == 0x200c || cps[i] == 0x200d) {
            if (!idna_joiner_ok(cps, n, i)) return 0;
            continue;
        }
        r = idna_range_of(cps[i]);
        if (r < 0 || IDNA_RANGES[r].outcome != IDNA_KEEP) return 0;
    }
    return 1;
}

int idna_domain_to_ascii(const char *domain, size_t len, char **out, size_t *out_len)
{
    uint32_t *cps = NULL, *folded = NULL, *norm = NULL;
    int n, fn, nn = 0, i, start, ok = 1, nlabels = 0;
    char *result = NULL;
    size_t rn = 0, cap;

    *out = NULL;
    n = utf8_to_cps(domain, len, &cps);
    if (n < 0) return -1;
    fn = map_uts46(cps, n, &folded);
    free(cps);
    if (fn < 0) return -1;   /* a DISALLOWED code point: §4.2's failure, which is what makes new URL() throw */
    /* UTS-46 step 2: NFC. A precomposed and a decomposed spelling of the same domain are the same domain, and
       without this they would be two different A-labels. */
    nn = unicode_normalize(&norm, folded, fn, UNICODE_NFC, NULL, idna_realloc);
    free(folded);
    if (nn < 0) return -1;

    cap = (size_t)nn * 8 + 16;
    result = malloc(cap);
    CHECK(result, "idna: OOM building an A-label");

    /* steps 3-4: one label at a time, split on U+002E. */
    start = 0;
    for (i = 0; i <= nn; i++) {
        int end = (i == nn || norm[i] == '.') ? i : -1;
        if (end < 0) continue;
        {
            int llen = end - start, j, has_non_ascii = 0, is_a_label;
            char label[512];
            int label_n = 0;

            for (j = start; j < end; j++) if (norm[j] >= 0x80) has_non_ascii = 1;
            is_a_label = llen >= 4 && norm[start] == 'x' && norm[start + 1] == 'n' &&
                         norm[start + 2] == '-' && norm[start + 3] == '-';
            /* THE `xn--` PREFIX IS TESTED FIRST. Testing for non-ASCII first sent `xn--a-Ä` down the ENCODE
               path and produced `xn--xn--a--...`, where §4's step 4.1 says an A-label carrying a non-ASCII
               code point is simply invalid — the corpus calls that P4. */
            if (is_a_label) {
                uint32_t dec[512];
                char body[512];
                int dn, k;
                if (has_non_ascii) { ok = 0; break; }
                for (k = 0; k < llen - 4; k++) body[k] = (char)norm[start + 4 + k];
                dn = idna_punycode_decode(body, (size_t)(llen - 4), dec,
                                          (int)(sizeof(dec) / sizeof(dec[0])));
                if (dn < 0) { ok = 0; break; }
                /* §4.1 applies to what the label DECODES to, which nothing else has looked at — without this
                   an A-label is a way to smuggle any code point at all into a domain. */
                if (!idna_label_is_valid(dec, dn)) { ok = 0; break; }
                for (k = 0; k < llen; k++) label[k] = (char)norm[start + k];
                label_n = llen;
            } else {
                /* §4.1 applies to EVERY label, not only to a decoded one. The mapping has already made every
                   code point valid, so what this catches is the LEADING COMBINING MARK — `a.b.̈c.d` has one
                   and is not a domain. */
                if (!idna_label_is_valid(norm + start, llen)) { ok = 0; break; }
                if (has_non_ascii) {
                    int e;
                    memcpy(label, "xn--", 4);
                    e = idna_punycode_encode(norm + start, llen, label + 4, (int)sizeof(label) - 5);
                    if (e < 0) { ok = 0; break; }
                    label_n = e + 4;
                } else {
                    for (j = 0; j < llen; j++) label[j] = (char)norm[start + j];
                    label_n = llen;
                }
            }
            /* NO LENGTH CAP. WHATWG calls UTS-46 with VerifyDnsLength=FALSE, so the 63-byte label and
               253-byte domain limits are not its errors — the corpus marks both A4_1 and A4_2 "(ignored)",
               and enforcing them rejected domains every browser accepts. */
            if (rn + (size_t)label_n + 2 > cap) {
                cap = (rn + (size_t)label_n + 2) * 2;
                result = realloc(result, cap);
                CHECK(result, "idna: OOM building an A-label");
            }
            /* THE SEPARATOR IS BETWEEN LABELS, not "before a non-empty one". Writing it only when something
               was already output DROPPED every empty label, so `..xn--hdh782b` came back as `xn--hdh782b` —
               a different domain, and one whose empty labels the caller can no longer refuse. */
            if (nlabels++) result[rn++] = '.';
            memcpy(result + rn, label, (size_t)label_n);
            rn += (size_t)label_n;
        }
        start = i + 1;
    }
    free(norm);
    if (!ok) { free(result); return -1; }
    result[rn] = 0;
    *out = result;
    if (out_len) *out_len = rn;
    return 0;
}

/* Everything above is bytes; the caller frees. */
void idna_free(char *s) { free(s); }
