/* GENERATED by engine/idlgen.mjs from canonical Web IDL (@webref/idl) — DO NOT EDIT.
 * The member SHAPE (name, kind, readonly, operation arity) of this Blink folder's interfaces, straight from
 * the spec. The component's hand-written BEHAVIOR is merged over this by idl_bind (impl-by-name); an unmodelled
 * operation DCHECKs "unsupported" when actually called (loud in dev, a compiled-out noop in release). */
#ifndef IDL_GEN_CORE_INTERSECTION_OBSERVER
#define IDL_GEN_CORE_INTERSECTION_OBSERVER
#include "bindings/idl.h"

static const IdlGenMember IntersectionObserver_IDL[] = {
  { "root", IDL_GEN_ATTR, 1, 0 },
  { "rootMargin", IDL_GEN_ATTR, 1, 0 },
  { "scrollMargin", IDL_GEN_ATTR, 1, 0 },
  { "thresholds", IDL_GEN_ATTR, 1, 0 },
  { "delay", IDL_GEN_ATTR, 1, 0 },
  { "trackVisibility", IDL_GEN_ATTR, 1, 0 },
  { "observe", IDL_GEN_OP, 0, 1 },
  { "unobserve", IDL_GEN_OP, 0, 1 },
  { "disconnect", IDL_GEN_OP, 0, 0 },
  { "takeRecords", IDL_GEN_OP, 0, 0 },
};
#define IntersectionObserver_IDL_N 10

#endif
