/* The first available font's metrics. See font_metrics.h for which face this is, for which of §6.1.1's metrics
   are the spec's own numbers rather than this component's, for why the ascent is the other kind of answer, and
   for what is deliberately absent. */
#include "check.h"
#include "core/css/css_length.h"
#include "core/css/font_metrics.h"
#include "core/fonts/default_font_data.h"
#include "core/fonts/open_type_metrics.h"

/* THE FACE, READ ONCE. css-fonts-4 §5.2 "Matching font styles" makes this user agent's default font the first
   available font of every element of every document ("or a user agent's default font if none are available"),
   so there is exactly one of these and it is the same one in every realm.
   A MODULE STATIC IS THE RIGHT ANSWER HERE AND IT IS WORTH SAYING WHY, because a fact answered from one place
   for many agents is normally the defect CLAUDE.md names. What makes this the exception is that the fact is a
   property of the BINARY and not of any document: `DEFAULT_FONT_SFNT` is a `const` array in the image, nothing
   below allocates, nothing below writes, and the struct holds only offsets into those constant bytes — so
   there is no per-realm object to come out under one flow's ownership and no state for a COW delta to capture.
   The day a page's own `@font-face` bytes are parsed, THAT face belongs to a document and does not live here.
   READ ON FIRST USE rather than at some init hook, because the operation is idempotent over constant data: two
   flows racing into it compute the same bytes into the same struct. */
static OpenTypeMetrics g_default_face;
static bool g_default_face_read;

static const OpenTypeMetrics *font_metrics_face(void)
{
    if (!g_default_face_read) {
        /* A CHECK AND NOT A DCHECK — the split is CLAUDE.md's and this is its data-integrity arm rather than
           its invariant arm. A user agent whose own default font will not parse has no metric for any element
           of any document, so every length it goes on to report is a fabrication and every line break derived
           from one is a measurement of nothing. That must not proceed in a release build either, which is
           exactly what separates it from the dev-only asserts around it. The bytes are generated by
           engine/fontsubset.mjs from a pinned input, so reaching this means the generated file was hand-edited
           or the linker gave us something else. */
        CHECK(open_type_metrics_read(&g_default_face, DEFAULT_FONT_SFNT, DEFAULT_FONT_SFNT_LEN),
              "this user agent's own default font — css-fonts-4 §5.2's \"a user agent's default font if none "
              "are available\", the first available font of every element of every document — did not parse. "
              "core/fonts/default_font_data.c is GENERATED by engine/fontsubset.mjs out of a face pinned by "
              "sha256; re-run the generator rather than editing the bytes. g_default_face.reject names which "
              "OpenType rule the shipped bytes broke");
        g_default_face_read = true;
    }
    return &g_default_face;
}

/* §6.1.1's ASSUMED X-HEIGHT, in the section's own words: "in the cases where it is impossible or impractical
   to determine the x-height, a value of 0.5em must be assumed". THE ANTECEDENT SURVIVED THE FACE, and for a
   reason that is checkable rather than asserted: an x-height is 'OS/2' — OS/2 and Windows Metrics Table's
   `sxHeight`, and the metrics-only sfnt core/fonts/default_font_data.c ships carries no 'OS/2' at all —
   engine/fontsubset.mjs lists every table it drops and why, and 'OS/2' is dropped because nothing reads it.
   So this is still a citation and not a calibration.
   IT IS NOT DERIVABLE FROM THE "0" GLYPH'S ADVANCE, which the face below MEASURES. The two numbers were equal
   only while both were §6.1.1's own assumptions for a user agent that could measure neither, and they are not
   equal any more: this stays 0.5 and the advance of "0" is whatever the face says. */
double font_metrics_x_height_em(void)
{
    return 0.5;
}

/* THE ADVANCE MEASURE OF THE GLYPH THE FACE ACTUALLY USES — css-values-4 §6.1.1's own defined term, "its
   advance width or height, whichever is in the inline axis of the element", answered off the first available
   font's OpenType tables and divided by the em the face states.
   A CODEPOINT THE FACE DOES NOT COVER IS NOT AN ERROR AND IS NOT ZERO. OpenType 'cmap' — Character to Glyph
   Index Mapping Table §Table overview reserves glyph 0 for exactly this — "character codes that do not
   correspond to any glyph in the font should be mapped to glyph index 0. The glyph at this location must be a
   special glyph representing a missing character, commonly known as .notdef" — and css-fonts-4 §5.2 "Matching
   font styles" says what a user agent with nothing else does with it: "If a particular character cannot be
   displayed using any font, the user agent should indicate by some means that a character is not being
   displayed, displaying either a symbolic representation of the missing glyph (e.g. using a Last Resort Font)
   or using the missing character glyph from a default font". THIS user agent installs no faces and loads none,
   so §5.2's earlier step — "if there are no more font families to be evaluated and no matching face has been
   found, then the user agent performs an installed font fallback procedure" — finds nothing, and the glyph
   that gets drawn IS .notdef. Its advance is a real measurement of the glyph that is really there, which is
   the number a line break has to be computed from.
   THAT IS A DIFFERENT QUESTION FROM §6.1.1's `ch` AND `ic`, and the entry below is the other one. */
double font_metrics_advance_measure_em(uint32_t codepoint, FontMetricsAdvanceDirection direction)
{
    const OpenTypeMetrics *face = font_metrics_face();
    uint16_t glyph;

    DCHECK(direction == FONT_METRICS_ADVANCE_HORIZONTAL || direction == FONT_METRICS_ADVANCE_VERTICAL,
           "css-values-4 §6.1.1's advance measure was asked for in neither of the two directions a glyph has "
           "an advance in. The enum is OpenType's own pair — 'hmtx' — Horizontal Metrics Table's advanceWidth "
           "and 'vmtx' — Vertical Metrics Table's advanceHeight — so a third value is a caller that resolved "
           "the element's `writing-mode` and `text-orientation` into something that is not an answer");
    DCHECK(codepoint <= 0x10FFFF && !(codepoint >= 0xD800 && codepoint <= 0xDFFF),
           "css-values-4 §6.1.1's advance measure was asked for something that is not a Unicode scalar value — "
           "a surrogate code point or one past U+10FFFF. A glyph is selected for a SCALAR VALUE, and OpenType "
           "'cmap' — Character to Glyph Index Mapping Table maps nothing else, so a lone surrogate here is a "
           "caller that split a string between its two halves");
    DCHECK(face->units_per_em >= 16 && face->units_per_em <= 16384,
           "the first available font's unitsPerEm is outside the range OpenType 'head' — Font Header Table "
           "fixes for it (\"Set to a value from 16 to 16384\"). open_type_metrics_read rejects a face where it "
           "is, so a face in hand with a bad divisor is a struct written after the read rather than by it — "
           "and it is the DIVISOR of every length below, so a zero here is every font-relative length on every "
           "page becoming infinite at once");

    glyph = open_type_metrics_glyph_id(face, codepoint);
    /* THE DIVISION IS WHERE THE DESIGN UNIT BECOMES THE EM, and it is the whole reason this entry can keep
       returning a ratio across a change of face: OpenType states every advance "in font design units" and
       'head'.unitsPerEm is what the em is worth in them. */
    if (direction == FONT_METRICS_ADVANCE_HORIZONTAL)
        return (double)open_type_metrics_advance_width(face, glyph) / face->units_per_em;
    return (double)open_type_metrics_advance_height(face, glyph) / face->units_per_em;
}

/* §6.1.1's MUST-ASSUME ADVANCE MEASURES, one row per (GLYPH, DIRECTION) because that is the shape a face's own
   metrics have and because the section states one of them per direction and the other over both:
     "0"  — "in the cases where it is impossible or impractical to determine the measure of the '0' glyph, it
            must be assumed to be 0.5em WIDE BY 1em TALL", which the section then restates as a consequence
            about the unit: "the ch unit falls back to 0.5em in the general case, and to 1em when it would be
            typeset upright". TWO NUMBERS, and which one is the advance measure is the direction.
     "水" — "in the cases where it is impossible or impractical to determine the IDEOGRAPHIC ADVANCE MEASURE,
            it must be assumed to be 1em". The sentence is stated over the advance measure ITSELF, which is
            already the direction-selected quantity, so it fixes the same number whichever direction selects
            it — and the two identical rows below say that on purpose rather than by a missing row.
   WRITING THE `水` ROWS OUT TWICE IS THE POINT, NOT REDUNDANCY. A single direction-independent entry would
   make the caller's obligation to resolve the direction disappear for one glyph and remain for the other,
   which is exactly how the two units came apart before this entry existed. */
static const struct { uint32_t cp; FontMetricsAdvanceDirection dir; double em; } FONT_METRICS_ASSUMED_ADVANCE[] = {
    { 0x0030, FONT_METRICS_ADVANCE_HORIZONTAL, 0.5 },
    { 0x0030, FONT_METRICS_ADVANCE_VERTICAL,   1.0 },
    { 0x6C34, FONT_METRICS_ADVANCE_HORIZONTAL, 1.0 },
    { 0x6C34, FONT_METRICS_ADVANCE_VERTICAL,   1.0 },
};

/* §6.1.1's `ch` AND `ic` — "the TYPICAL advance measure of European alphanumeric characters" and "the TYPICAL
   advance measure of CJK letters", which the section measures as the advance of one named glyph "in the font
   used to render it" and then, for the case where that cannot be done, FIXES.
   WHY THIS IS A SECOND ENTRY AND NOT A ROW IN THE ONE ABOVE. The two are the same measurement under different
   ANTECEDENTS, and conflating them is wrong in both directions. §6.1.1 states its assumed value over "the
   cases where it is impossible or impractical to determine the measure of the '0' glyph"; a face with no such
   glyph is that case, and answering the unit with .notdef's advance would report a measurement of the tofu box
   as the width of a digit. Going the other way, answering a LINE BREAK's advance with 1em because §6.1.1 says
   to assume that for the `ic` unit would make every uncovered character in a run exactly one em wide, which is
   the length-alone failure the whole face exists to prevent. So: the entry above measures the glyph that gets
   drawn, this one answers the unit, and each is stated where its own antecedent is true.
   THE ANTECEDENT HAS TWO WAYS TO HOLD and both are the face's own doing, which is why it is asked of the face
   rather than assumed once. The face may have no glyph for the codepoint at all — open_type_metrics_covers is
   OpenType's reserved glyph 0 read as the negative answer it is. Or the face may have the glyph and no metric
   for the axis: 'vhea'/'vmtx' are optional in OpenType and most Latin faces omit them, so a VERTICAL advance
   measure is undeterminable for exactly the reason §6.1.1's clause describes. That second arm narrows the day
   css-writing-modes-4 §5.1.1 "Vertical Typesetting and Font Features"'s synthesis is built — "the UA must
   synthesize vertical font metrics for fonts that lack them. (This specification does not define heuristics
   for synthesizing such metrics.)" — at which point the measure becomes determinable and the assumption stops
   applying. Until then the crash that names that work lives at the entry above, where a line break asks. */
double font_metrics_typical_advance_measure_em(uint32_t codepoint, FontMetricsAdvanceDirection direction)
{
    const OpenTypeMetrics *face = font_metrics_face();
    unsigned i;

    DCHECK(direction == FONT_METRICS_ADVANCE_HORIZONTAL || direction == FONT_METRICS_ADVANCE_VERTICAL,
           "css-values-4 §6.1.1's `ch` or `ic` was asked for in neither of the two directions a glyph has an "
           "advance in — see the entry above, whose enum this is");
    if (open_type_metrics_covers(face, codepoint) &&
        (direction == FONT_METRICS_ADVANCE_HORIZONTAL || face->has_vertical))
        return font_metrics_advance_measure_em(codepoint, direction);

    for (i = 0; i < sizeof(FONT_METRICS_ASSUMED_ADVANCE) / sizeof(FONT_METRICS_ASSUMED_ADVANCE[0]); i++)
        if (FONT_METRICS_ASSUMED_ADVANCE[i].cp == codepoint && FONT_METRICS_ASSUMED_ADVANCE[i].dir == direction)
            return FONT_METRICS_ASSUMED_ADVANCE[i].em;
    DFAIL("css-values-4 §6.1.1 \"Font-relative Lengths: the em, rem, ex, rex, cap, rcap, ch, rch, ic, ric, lh, "
          "rlh units\" states a MUST-ASSUME advance measure for the \"0\" (U+0030) glyph of `ch` and the \"水\" "
          "(U+6C34) glyph of `ic` and for NO OTHER, and this entry answers those two units and nothing else. A "
          "third row would be an assumption the section never made, on behalf of a unit that does not exist. "
          "WHAT THE CALLER ALMOST CERTAINLY WANTS IS `font_metrics_advance_measure_em` — the advance of the "
          "glyph the face actually uses, which answers for EVERY Unicode scalar value and needs no assumption "
          "because it is a measurement. The only callers that belong here are the ones resolving §6.1.1's own "
          "`ch`/`rch` and `ic`/`ric`");
    return 0.0;
}

/* CSS 2.2 §10.8.1 "Leading and half-leading"'s `A` AND `D`, READ OFF THE FACE — "CSS assumes that every font
   has font metrics that specify a characteristic height above the baseline and a depth below it. In this
   section we use A to mean that height (for a given font at a given size) and D the depth."
   THEY WERE PICKED CONSTANTS AND THEY ARE NOT ANY MORE, and the sentence that changed it is §10.8.1's own
   note, which names the tables and their order: "It is recommended that implementations that use OpenType or
   TrueType fonts use the metrics 'sTypoAscender' and 'sTypoDescender' from the font's OS/2 table for A and D
   (after scaling to the current element's font size). IN THE ABSENCE OF THESE METRICS, the 'Ascent' and
   'Descent' metrics from the HHEA table should be used." The face this engine ships carries 'hhea' and no
   'OS/2', so the note's second sentence is not a fallback taken for convenience — it is the branch the note
   states for exactly this face, and a picked constant beside it would be the plausible number CLAUDE.md's NO
   STUBS forbids where the spec computes a real one. That the pair used to be picked is why the asserts below
   read as they do: each one was written to keep two INVENTED numbers describing one face, and every one of
   them now checks a face against a spec instead — which is strictly the stronger test and is why none of them
   was deleted with the constants.
   THE SIGN FLIP IS THE ONE PLACE THE TWO VOCABULARIES DISAGREE. OpenType's 'hhea'.descender is an FWORD
   measured UP from the baseline, so an ordinary face's is negative; §10.8.1's `D` is "a depth below" it and is
   positive. Negating here rather than at each reader is what keeps the assert below ("a face whose depth is
   negative has its baseline outside its own em box") a statement about the FACE and not about a sign
   convention.
   `A` IS STILL A FACT AND NOT A DERIVATION, which is why both keep their CSS_ENV_* rows. core/frame/
   viewport.h's test is whether the model picked one point out of a range the environment leaves free, and it
   still did: what is picked is now the FACE rather than the ratio, and a reader with a different default font
   reads a different `1cap` against the same `fontSize`. */
static double font_metrics_ascent_em(void)
{
    const OpenTypeMetrics *face = font_metrics_face();

    DCHECK(!face->has_os2,
           "the first available font carries an 'OS/2' — OS/2 and Windows Metrics Table, and CSS 2.2 §10.8.1 "
           "\"Leading and half-leading\"'s note prefers ITS metrics for `A` and `D`: \"use the metrics "
           "'sTypoAscender' and 'sTypoDescender' from the font's OS/2 table ... In the absence of these "
           "metrics, the 'Ascent' and 'Descent' metrics from the HHEA table should be used\". This entry reads "
           "'hhea', which is the ABSENCE branch, so a face with 'OS/2' is being measured through the spec's "
           "second choice. BUILD sTypoAscender/sTypoDescender in core/fonts/open_type_metrics.c and prefer "
           "them here — the flag that fired is the one that exists so this cannot happen quietly");
    return (double)face->hhea_ascender / face->units_per_em;
}

static double font_metrics_descent_em(void)
{
    const OpenTypeMetrics *face = font_metrics_face();

    DCHECK(!face->has_os2,
           "the first available font carries an 'OS/2' table whose sTypoDescender CSS 2.2 §10.8.1's note "
           "prefers over the 'hhea' Descent this entry reads — the same branch the ascent above names");
    /* NEGATED: an FWORD measured up from the baseline becomes §10.8.1's depth below it. */
    return (double)-face->hhea_descender / face->units_per_em;
}

CssPx font_metrics_ascent_px(JSContext *realm, CssPx font_size)
{
    if (realm == NULL)
        DFAIL("CSS 2.1 §10.8.1 (Leading and half-leading)'s `A` was asked for with no realm. The NUMBER needs "
              "none — this user agent's installed face is the same face whether or not the document is being "
              "presented, which is why its row in core/frame/viewport.c's seam is not a presented one — but "
              "the SOURCE KEY the fact is minted under is keyed on the document that read it, so a child "
              "navigable's environment and its parent's stay two questions rather than one. The caller is a "
              "css-values-4 §6.1.1 unit resolving on an element, and every element has a node document; one "
              "that is no navigable's ACTIVE document reaches this exactly as core/css/font_size_functions.c's "
              "`medium` does and takes the same answer");
    DCHECK(font_metrics_ascent_em() >= font_metrics_x_height_em(),
           "the first available font's ascent is BELOW the x-height css-values-4 §6.1.1 assumes for it. No "
           "face has a characteristic height above the baseline smaller than the height of its own lowercase "
           "letters, so the measured metric and the assumed one no longer describe one face — and the "
           "consequence is visible in the units §6.1.1 defines over them: an undeterminable cap-height falls "
           "back to the ascent, so a `1cap` box would come out SHORTER than a `1ex` one. The x-height is "
           "§6.1.1's assumption because the shipped face has no 'OS/2'.sxHeight to measure; a face whose own "
           "ascent falls under half an em is one for which that assumption is the wrong one");
    /* THE PRODUCT IS FORMED HERE so the two facts are unioned by css_length.h's arithmetic rather than by
       whichever caller remembered to: the answer is a joint function of the reader's font size, which the
       operand already carries, and of this user agent's face. */
    return css_px_mul(font_size, css_px_env(CSS_ENV_FONT_ASCENT, realm, font_metrics_ascent_em()));
}

CssPx font_metrics_normal_line_height_px(JSContext *realm, CssPx font_size)
{
    CssPx descent;

    if (realm == NULL)
        DFAIL("CSS 2.1 §10.8.1 (Leading and half-leading)'s `AD` was asked for with no realm — the same "
              "question the ascent above answers, for the same reason: the two metrics are a source key each, "
              "and a key is keyed on the document that read it");
    /* §10.8's OWN RECOMMENDATION, ASSERTED OVER THE PAIR — "we recommend a used value for 'normal' between
       1.0 to 1.2". It is a statement about the SUM, which is why it could not be checked where `A` was picked
       and is checked here, at the one place the sum is formed. A user agent is permitted to disagree with a
       recommendation; what it must not do is disagree by ACCIDENT, which is what an unasserted pair of picked
       numbers drifting apart would be. The bounds are inclusive because the spec's "between 1.0 to 1.2" names
       both endpoints as acceptable values rather than as strict limits. */
    DCHECK(font_metrics_ascent_em() + font_metrics_descent_em() >= 1.0 &&
               font_metrics_ascent_em() + font_metrics_descent_em() <= 1.2,
           "the first available font's `A` and `D` sum to a `normal` line height OUTSIDE the range CSS 2.1 "
           "§10.8 recommends — \"we recommend a used value for 'normal' between 1.0 to 1.2\". Under 1.0 "
           "successive lines overlap at the default font size and over 1.2 every block of text on every page "
           "is loosely set. The pair is no longer picked, so this is no longer a number to move: it is a "
           "statement about the FACE core/fonts/default_font_data.c ships, and a face outside the range is a "
           "face this user agent should not be defaulting to — or a `normal` this engine states its "
           "disagreement about on purpose, here");
    /* §10.8.1: "we also define AD = A + D, the distance from the top to the bottom". The sum is formed over
       the two lengths rather than over the two ratios so that BOTH facts reach the result — a page reads the
       ascent through `1cap` and the sum through `1lh`, and a domain naming only one of them would leave the
       arm where the other reader's face differs unexplored. */
    descent = font_metrics_descent_px(realm, font_size);
    return css_px_add(font_metrics_ascent_px(realm, font_size), descent);
}

CssPx font_metrics_descent_px(JSContext *realm, CssPx font_size)
{
    if (realm == NULL)
        DFAIL("CSS 2.2 §10.8.1 (Leading and half-leading)'s `D` was asked for with no realm — the same "
              "question the ascent above answers, for the same reason: the two metrics are a source key each, "
              "and a key is keyed on the document that read it");
    /* THE SUM'S BOUND IS ASSERTED WHERE THE SUM IS FORMED and not here, because §10.8's recommendation is a
       statement about `normal` and therefore about `AD` — a bound restated over one term would be this file
       deciding how the pair splits, which is exactly the free choice the two picked numbers ARE. What is
       asserted about `D` alone is the one thing §10.8.1's own definition fixes: it is a DEPTH BELOW the
       baseline, so a face whose depth is negative has its baseline outside its own em box and every A' / D'
       split below it comes out on the wrong side of the line. */
    DCHECK(font_metrics_descent_em() >= 0.0,
           "the first available font's `D` is NEGATIVE. CSS 2.2 §10.8.1 defines it as \"a depth below\" "
           "the baseline, so a negative one puts the baseline below the bottom of the face and makes every "
           "half-leading split in core/layout/line_box.c place a box above a line it sits below");
    return css_px_mul(font_size, css_px_env(CSS_ENV_FONT_DESCENT, realm, font_metrics_descent_em()));
}
