/* GENERATED by engine/idlgen.mjs from canonical Web IDL (@webref/idl) — DO NOT EDIT.
 * The member SHAPE (name, kind, readonly, operation arity) of this Blink folder's interfaces, straight from
 * the spec. The component's hand-written BEHAVIOR is merged over this by idl_bind (impl-by-name); an unmodelled
 * operation DCHECKs "unsupported" when actually called (loud in dev, a compiled-out noop in release). */
#ifndef IDL_GEN_CORE_RESIZE_OBSERVER
#define IDL_GEN_CORE_RESIZE_OBSERVER
#include "bindings/idl.h"

static const IdlGenMember ResizeObserver_IDL[] = {
  { "observe", IDL_GEN_OP, 0, 1 },
  { "unobserve", IDL_GEN_OP, 0, 1 },
  { "disconnect", IDL_GEN_OP, 0, 0 },
};
#define ResizeObserver_IDL_N 3

#endif
