/* THE GENERATOR FOR LEXBOR'S `css/unit` TABLES, WHICH THOSE TABLES HAVE ALWAYS NAMED AND THIS TREE HAS NEVER
 * HAD. Both `source/lexbor/css/unit/const.h` and `.../unit/res.h` open with "This file generated by the script
 * utils/lexbor/css/names.py! Do not change this file!", and `utils/` is not vendored — so the instruction
 * pointed at nothing, and the only two ways to change a unit were to hand-edit a perfect hash or to leave the
 * table wrong. It was left wrong: lexbor's absolute+relative set is a STRICT SUBSET of the `<length>` units
 * this engine's `css_length_is_length_unit` admits, and `lxb_css_property_state_length` returns FALSE for a
 * dimension whose unit misses, which DROPS the declaration and leaves the initial value behind with nothing
 * anywhere to say so. A `height: 100dvh` was indistinguishable from `height: 100zzq`.
 *
 * WHAT MAKES THIS SAFE TO TRUST IS A POSITIVE CONTROL AND NOT AN ARGUMENT. Every rule below was read off the
 * artifacts (`core/shs.c`'s hash macro, `css/unit.c`'s lookups, the committed tables' own shape) and then
 * CHECKED by regenerating the tables as they stood before any unit was added and diffing: BYTE-IDENTICAL, both
 * files, including the table sizes, the bucket each key lands in, the blank rows and the trailing spaces. A
 * generator that reproduces its subject exactly is a generator whose breakdown is worth reading; one that
 * merely looks right is a second copy of a perfect hash, which is the silent-corruption risk this file exists
 * to remove. `--check` re-runs that comparison against whatever is committed, so the control is a COMMAND a
 * reader runs rather than a claim this comment makes.
 *
 * THE HASH IS `core/shs.c`'s `lexbor_shs_make_id_lower_m` and nothing else:
 *   id = ((((lower[k[0]] * lower[k[n-1]]) * lower[k[0]]) + n) % table_size) + 1
 * `table_size` is stored in the root entry's `key_len` field, and the array is `table_size + 1` long because
 * index 0 IS that root. `lexbor_shs_entry_get_lower_static` walks `next` on a collision and STOPS EARLY when
 * it meets an entry whose `key_len` exceeds the one it was asked for — so a chain must be sorted by key length
 * ascending or a shorter key behind a longer one becomes unreachable. This generator never builds a chain: it
 * searches for the smallest COLLISION-FREE `table_size`, which is what upstream did too — every `next` in the
 * committed tables is 0. The search floor of 5 is not a guess either; it is the one value that reproduces the
 * committed two-key tables (`frequency` and `duration` are sized 5, not the 2 a bare smallest-fit finds).
 *
 * THE ONE HARD INVARIANT IS THAT A DATA ROW'S INDEX EQUALS ITS ENUM VALUE, because `lxb_css_unit_by_id` is
 * `&lxb_css_unit_data[id]` and `lxb_css_property_state_length` stores `unit->unique` as the parsed unit — so
 * the id round-trips through the cascade and back out through `css/value.c`'s serialization, which is the path
 * `core/css/css_style_declaration.c` re-parses. Both are emitted from ONE ordered list below for that reason.
 *
 * THE NEW UNITS ARE RELATIVE ONES AND ARE PLACED IN THE RELATIVE FAMILY, not appended past `duration` where
 * they would renumber nothing. css-values-4 §6.1.2.1 defines the small, large and dynamic viewport sizes and
 * CSS Conditional 5 §7 the container-relative units; both are relative lengths, and §6.1.1's `rcap`, `rch`,
 * `rex` and `ric` are the root-relative half of a font-relative table whose other half lexbor already had.
 * Placing them truthfully shifts `angle`, `frequency`, `resolution` and `duration` upward, which is safe and
 * was CHECKED rather than assumed: no file in this tree tests a unit id against `LXB_CSS_UNIT_*__BEGIN` or
 * `__LAST_ENTRY`, and no unit id is persisted or compared numerically anywhere — every reference is symbolic.
 *
 * RUN: `node engine/cssunitgen.mjs` writes both files; `node engine/cssunitgen.mjs --check` writes nothing and
 * reports whether the committed files still match, and whether lexbor's set still covers the engine's. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CONST_H = join(ROOT, 'engine/lexbor/source/lexbor/css/unit/const.h');
const RES_H = join(ROOT, 'engine/lexbor/source/lexbor/css/unit/res.h');
const NAMESPACE_C = join(ROOT, 'engine/host/browser/core/css/css_namespace.c');

/* Lexbor's own generator input, restored. The families are lexbor's, not this engine's: `angle`, `frequency`,
   `resolution` and `duration` are units the `<length>` table below has nothing to say about, so this list
   cannot be derived from the engine's — what CAN be derived, and is, is the CONTAINMENT `--check` asserts. */
const FAM = {
  absolute: { t: 'lxb_css_unit_absolute_t', p: 'ABSOLUTE', u: ['Q', 'cm', 'in', 'mm', 'pc', 'pt', 'px'] },
  relative: {
    t: 'lxb_css_unit_relative_t', p: 'RELATIVE', u: [
      /* css-values-4 §6.1.1 "Font-relative Lengths: the em, rem, ex, rex, cap, rcap, ch, rch, ic, ric, lh,
         rlh units" — all twelve. Lexbor carried the six that are not root-relative. */
      'cap', 'ch', 'em', 'ex', 'ic', 'lh', 'rcap', 'rch', 'rem', 'rex', 'ric', 'rlh',
      /* §6.1.2 viewport-percentage lengths, in all four of §6.1.2.1's viewport sizes. Lexbor carried the
         DEFAULT family only. The four are separate units and must stay separate ids: `100dvh === 100lvh` is a
         comparison a mobile bundle branches on, and one id for four families decides it. */
      'vb', 'vh', 'vi', 'vmax', 'vmin', 'vw',
      'svb', 'svh', 'svi', 'svmax', 'svmin', 'svw',
      'lvb', 'lvh', 'lvi', 'lvmax', 'lvmin', 'lvw',
      'dvb', 'dvh', 'dvi', 'dvmax', 'dvmin', 'dvw',
      /* CSS Conditional 5 §7 "Container Relative Lengths: the cqw, cqh, cqi, cqb, cqmin, cqmax units". */
      'cqb', 'cqh', 'cqi', 'cqmax', 'cqmin', 'cqw',
    ],
  },
  angle: { t: 'lxb_css_unit_angle_t', p: 'ANGLE', u: ['deg', 'grad', 'rad', 'turn'] },
  frequency: { t: 'lxb_css_unit_frequency_t', p: 'FREQUENCY', u: ['Hz', 'kHz'] },
  resolution: { t: 'lxb_css_unit_resolution_t', p: 'RESOLUTION', u: ['dpcm', 'dpi', 'dppx', 'x'] },
  duration: { t: 'lxb_css_unit_duration_t', p: 'DURATION', u: ['ms', 's'] },
};
/* Each family is emitted in byte order, which is the order the committed tables are already in. Sorting here
   rather than by hand is why adding a unit above cannot put a data row out of step with its enum value. */
for (const f of Object.values(FAM)) f.u.sort();

const sym = (n) => 'LXB_CSS_UNIT_' + n.toUpperCase();
const lo = (c) => (c >= 65 && c <= 90 ? c + 32 : c);
const hid = (k, size) =>
  ((lo(k.charCodeAt(0)) * lo(k.charCodeAt(k.length - 1)) * lo(k.charCodeAt(0)) + k.length) % size) + 1;

/* THE SMALLEST TABLE SIZE THAT COLLIDES NO MORE THAN IT MUST. Two keys sharing a first byte, a last byte and
   a length hash identically at EVERY size, so a collision-free table is not always reachable: `rch` and `rlh`
   are both (r, h, 3) and always share a bucket. The search therefore targets that unavoidable floor rather
   than zero, which reproduces upstream's sizes wherever the floor IS zero and stays tight where it is not. */
function unavoidable(keys) {
  return keys.length - new Set(keys.map((k) => `${k[0]}|${k[k.length - 1]}|${k.length}`)).size;
}
function pickSize(keys) {
  const floor = unavoidable(keys);
  for (let size = Math.max(keys.length, 5); size < 8192; size++) {
    const seen = new Set();
    for (const k of keys) seen.add(hid(k, size));
    if (keys.length - seen.size === floor) return size;
  }
  throw new Error('no table size reaches the unavoidable collision floor');
}

/* THE CHAIN, WHICH `lexbor_shs_entry_get_lower_static` WALKS AND WHICH HAS ONE ORDERING RULE. That walk meets
   an entry and, when its `key_len` EXCEEDS the length being looked up, RETURNS NULL rather than following
   `next` -- so a chain must run shortest-first or a short key sitting behind a long one is unreachable and its
   declaration is dropped exactly as an unknown unit's is. Overflow entries take the lowest-numbered slot no
   key hashes to, which is upstream's own layout (read off `css/property/res.h`, where `wrap-flow` at its
   bucket chains to `wrap-through` parked at index 1). A slot no key hashes to is a slot no lookup STARTS at,
   so it is reachable only through the chain that owns it. */
function shsRows(keys) {
  const size = pickSize(keys), n = size + 1;
  const rows = Array.from({ length: n }, () => null);
  const buckets = new Map();
  for (const k of keys) {
    const b = hid(k, size);
    if (!buckets.has(b)) buckets.set(b, []);
    buckets.get(b).push(k);
  }
  for (const [b, ks] of buckets) {
    ks.sort((a, c) => a.length - c.length || (a < c ? -1 : 1));
    rows[b] = { key: ks[0], next: 0 };
  }
  let free = 1;
  for (const b of [...buckets.keys()].sort((a, c) => a - c)) {
    const ks = buckets.get(b);
    let prev = b;
    for (let i = 1; i < ks.length; i++) {
      while (free < n && rows[free] !== null) free++;
      if (free >= n) throw new Error('no free slot for a chained entry');
      rows[free] = { key: ks[i], next: 0 };
      rows[prev].next = free;
      prev = free;
    }
  }
  return { rows, size, n };
}

/* `lexbor_shs_entry_get_lower_static` (core/shs.c) TRANSCRIBED, so the table is proven by the walk that will
   read it rather than by the reasoning that built it. Every key must find itself and every non-key must find
   nothing -- a one-sided check would pass on a table that resolves everything. */
function simulate(rows, size, key) {
  let e = rows[hid(key, size)];
  const root = { key: null, next: 0 };
  const at = (i) => (i === 0 ? root : rows[i] ?? root);
  while (e !== null && e !== undefined && e.key !== null) {
    if (e.key.length === key.length) {
      if (e.key.toLowerCase() === key.toLowerCase()) return e.key.toLowerCase();
      e = at(e.next);
    } else if (e.key.length > key.length) return null;
    else e = at(e.next);
  }
  return null;
}
const NEGATIVE = ['zzq', 'dv', 'dvhh', 'cq', 'cqmaxx', 'rc', 'rlhh', 'svmi', 'foo', 'r', 'vmaxx'];
function verify(label, keys) {
  const { rows, size, n } = shsRows(keys);
  const R = Array.from({ length: n }, (_, i) => (i === 0 ? { key: null, next: 0 } : rows[i] ?? { key: null, next: 0 }));
  for (const k of keys) {
    if (simulate(R, size, k) !== k.toLowerCase()) throw new Error(`${label}: "${k}" does not resolve to itself`);
    if (simulate(R, size, k.toUpperCase()) !== k.toLowerCase()) throw new Error(`${label}: "${k}" fails ASCII-case-insensitively`);
  }
  const inSet = new Set(keys.map((k) => k.toLowerCase()));
  for (const k of NEGATIVE) {
    if (inSet.has(k)) continue;
    if (simulate(R, size, k) !== null) throw new Error(`${label}: non-key "${k}" resolved`);
  }
  return `${label}: ${keys.length} keys, table ${size}, ${keys.length - new Set(keys.map((k) => hid(k, size))).size} chained, all resolve, ${NEGATIVE.length} negatives refused`;
}

function shs(name, keys) {
  const { rows, size, n } = shsRows(keys);
  const body = Array.from({ length: n }, (_, i) =>
    i === 0 ? `{NULL, NULL, ${size}, 0}`
      : rows[i] === null ? '{NULL, NULL, 0, 0}'
        : `{"${rows[i].key.toLowerCase()}", (void *) &lxb_css_unit_data[${sym(rows[i].key)}], ${rows[i].key.length}, ${rows[i].next}}`);
  return `static const lexbor_shs_entry_t ${name}[${n}] = \n{\n`
    + body.map((b, i) => `    ${b}${i === n - 1 ? '' : ', '}`).join('\n') + '\n};\n';
}

const order = [];
for (const f of Object.values(FAM)) for (const u of f.u) order.push(u);
const ids = new Map(order.map((u, i) => [u, i + 1]));
const hex = (v) => '0x' + v.toString(16).padStart(4, '0');

function banner(guard) {
  return '/*\n * Copyright (C) 2026 Alexander Borisov\n *\n'
    + ' * Author: Alexander Borisov <borisov@lexbor.com>\n */\n\n/*\n * Caution!\n'
    + ' * This file generated by the script "engine/cssunitgen.mjs"!\n * Do not change this file!\n */\n\n\n'
    + `#ifndef ${guard}\n#define ${guard}\n\n`;
}
function block(lines) {
  const w = Math.max(...lines.map((l) => l[0].length)) + 1;
  return 'typedef enum {\n'
    + lines.map((l) => `    ${l[0].padEnd(w)}= ${hex(l[1])},`).join('\n').replace(/,$/, '') + '\n}\n';
}

function constH() {
  let s = banner('LXB_CSS_UNIT_CONST_H') + '\n#include "lexbor/css/value/const.h"\n\n\n';
  s += block([['LXB_CSS_UNIT__UNDEF', 0], ['LXB_CSS_UNIT__LAST_ENTRY', order.length + 1]]) + 'lxb_css_unit_t;\n\n';
  for (const f of Object.values(FAM)) {
    const L = [[`LXB_CSS_UNIT_${f.p}__BEGIN`, ids.get(f.u[0])]];
    for (const u of f.u) L.push([sym(u), ids.get(u)]);
    L.push([`LXB_CSS_UNIT_${f.p}__LAST_ENTRY`, ids.get(f.u[f.u.length - 1]) + 1]);
    s += block(L) + f.t + ';\n\n';
  }
  return s + '\n\n#endif /* LXB_CSS_UNIT_CONST_H */\n';
}

function resH() {
  let s = banner('LXB_CSS_UNIT_RES_H').replace('\n\n#define', '\n#define')
    + '#include "lexbor/core/shs.h"\n#include "lexbor/css/unit/const.h"\n\n\n';
  s += 'static const lxb_css_data_t lxb_css_unit_data[LXB_CSS_UNIT__LAST_ENTRY] = \n{\n';
  const rows = [`{(lxb_char_t *) "#undef", 6, LXB_CSS_UNIT__UNDEF}`]
    .concat(order.map((u) => `{(lxb_char_t *) "${u}", ${u.length}, ${sym(u)}}`));
  s += rows.map((r, i) => `    ${r}${i === rows.length - 1 ? '' : ','}`).join('\n') + '\n};\n\n';
  s += shs('lxb_css_unit_absolute_relative_shs', [...FAM.absolute.u, ...FAM.relative.u]) + '\n';
  for (const [k, f] of Object.entries(FAM)) s += shs(`lxb_css_unit_${k}_shs`, f.u) + '\n';
  return s + '\n\n\n#endif /* LXB_CSS_UNIT_RES_H */\n';
}

/* THE CONTAINMENT THIS FILE EXISTS TO END, asked of BOTH artifacts rather than restated in either. The engine's
   `<length>` set is read out of `css_namespace.c`'s own block — which is the source `core/css/css_length.c`'s
   crash already names for this derivation — and every unit in it must be one lexbor's absolute+relative lookup
   resolves. A unit the engine calls a length and lexbor drops is not a parse error, it is a DECLARATION THAT
   DISAPPEARS, so this is the one comparison that must never come back short. It THROWS rather than reporting a
   smaller gap when it cannot find the block: a check that silently measures a subset reads as progress. */
function engineLengthUnits() {
  const src = readFileSync(NAMESPACE_C, 'utf8');
  const m = src.match(/\/\* <length>[\s\S]*?\*\/\n([\s\S]*?)\n\s*\/\* <angle>/);
  if (!m) throw new Error(`cannot find the <length> block in ${NAMESPACE_C} — the anchors moved; fix this `
    + 'extraction rather than letting the containment check answer about a subset');
  const u = [...m[1].matchAll(/"([A-Za-z]+)"/g)].map((x) => x[1].toLowerCase());
  if (u.length < 40) throw new Error(`the <length> block yielded only ${u.length} units, which is fewer than `
    + 'any reading of css-values-4 §6 admits — the extraction is wrong, not the table');
  return [...new Set(u)].sort();
}

const check = process.argv.includes('--check');
let bad = 0;

/* THE TABLES ARE PROVEN BEFORE THEY ARE WRITTEN, not after and not by a reader. */
try {
  console.log(verify('absolute_relative', [...FAM.absolute.u, ...FAM.relative.u]));
  for (const [k, f] of Object.entries(FAM)) console.log(verify(k, f.u));
} catch (e) {
  console.error('LOOKUP SIMULATION FAILED: ' + e.message);
  process.exit(1);
}

const want = { [CONST_H]: constH(), [RES_H]: resH() };
for (const [p, text] of Object.entries(want)) {
  if (check) {
    const have = readFileSync(p, 'utf8');
    console.log(`${have === text ? 'MATCH  ' : 'DIFFERS'}  ${p.slice(ROOT.length + 1)}`);
    if (have !== text) bad++;
  } else writeFileSync(p, text);
}

const lex = new Set([...FAM.absolute.u, ...FAM.relative.u].map((u) => u.toLowerCase()));
const gap = engineLengthUnits().filter((u) => !lex.has(u));
console.log(`containment: engine <length> units lexbor cannot resolve: ${gap.length}`
  + (gap.length ? ` -> ${gap.join(' ')}` : ''));
if (gap.length) bad++;
process.exit(bad ? 1 : 0);
