/* THE ENCODING STANDARD'S TABLES, generated from the standard's own machine-readable data.
 *
 * WHY GENERATED AND COMMITTED, the same reasons idnagen.mjs is. Two of the Encoding Standard's normative
 * artifacts are DATA rather than prose: §4.2's label table — 228 labels naming 40 encodings, including the ones
 * a page actually writes (`utf8`, `latin1`, `ansi_x3.4-1968`) — and §9.1's single-byte indexes, one 128-entry
 * map per legacy encoding. Hand-transcribing either is a guarantee of being subtly wrong somewhere nobody
 * checks, and "we support the labels we thought of" is not what a browser does with `<meta charset>`.
 *
 * The header is COMMITTED so the build needs no network. Re-run this deliberately when re-pinning, the same as
 * re-pinning lexbor, test262 or the wpt corpus.
 *
 * PINNED TWO WAYS. encodings.json carries no hash, so its SHAPE is asserted — the encoding count and the label
 * count, which is what would change if the registry did, and the generator stops rather than silently re-pinning
 * a table under a build checked against the old one. Each index file DOES carry the standard's own content
 * identifier, and each is EMITTED into the header beside its table: a moved index is then a visible diff in a
 * committed file rather than a decode that quietly changed.
 *
 * WHAT IS NOT GENERATED. The multi-byte CJK indexes (jis0208, big5, gb18030, euc-kr) are hundreds of kilobytes
 * each and each needs its own decoder ALGORITHM rather than a table lookup, so they are absent rather than
 * half-present — encoding.c crashes naming the encoding when a page asks for one, which is the honest state and
 * the work queue.
 *
 * Usage:  node engine/encgen.mjs
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const ENGINE = import.meta.dirname;
const OUT = join(ENGINE, "host", "browser", "core", "encoding", "encoding_table.h");
const BASE = "https://encoding.spec.whatwg.org/";

/* The registry's shape, asserted rather than trusted — see the file comment. */
const N_ENCODINGS = 40;
const N_LABELS = 228;

async function get(path) {
  const res = await fetch(BASE + path);
  if (!res.ok) { console.error(`[encgen] ${BASE}${path}: HTTP ${res.status}`); process.exit(1); }
  return res.text();
}

const registry = JSON.parse(await get("encodings.json"));
const encodings = registry.flatMap((g) => g.encodings.map((e) => ({ ...e, group: g.heading })));
const labels = encodings.flatMap((e) => e.labels);
if (encodings.length !== N_ENCODINGS || labels.length !== N_LABELS) {
  console.error(`[encgen] the registry now has ${encodings.length} encodings and ${labels.length} labels, and ` +
                `this generator is pinned to ${N_ENCODINGS}/${N_LABELS} — re-pin deliberately, as a commit of ` +
                `its own, so the diff in results has one cause.`);
  process.exit(1);
}

/* The single-byte group, read from the registry rather than listed here: the standard decides which encodings
   are single-byte, and a second list would be a second place for that to be true. */
const singleByte = registry.find((g) => g.heading === "Legacy single-byte encodings").encodings;

/* Parse an index file: `pointer \t code point \t # comment`, and every single-byte index has 128 entries. A
   pointer with no code point is absent, which the standard writes as a missing ROW rather than as a value —
   so the table is filled with 0 (U+0000 is never an index entry) and the decoder reads that as an error. */
function parseIndex(text) {
  const out = new Uint16Array(128);
  for (const line of text.split("\n")) {
    const m = /^\s*(\d+)\s+(0x[0-9A-Fa-f]+)/.exec(line);
    if (!m) continue;
    const p = Number(m[1]);
    if (p >= 128) { console.error(`[encgen] a single-byte index has pointer ${p}`); process.exit(1); }
    out[p] = Number(m[2]);
  }
  return out;
}

const indexes = [];
for (const e of singleByte) {
  const file = `index-${e.name.toLowerCase()}.txt`;
  /* ISO-8859-8-I shares ISO-8859-8's index — the standard gives it no file of its own, because the difference
     between the two is bidi handling and not the byte mapping. */
  const src = await get(e.name === "ISO-8859-8-I" ? "index-iso-8859-8.txt" : file);
  const id = /^#\s*Identifier:\s*(\S+)/m.exec(src);
  indexes.push({ name: e.name, table: parseIndex(src), id: id ? id[1] : "?" });
}

/* ---- emit ---------------------------------------------------------------------------------------------- */

const enumName = (n) => "ENC_" + n.toUpperCase().replace(/[^A-Z0-9]/g, "_");

let h = `/* GENERATED BY engine/encgen.mjs — DO NOT EDIT.
 *
 * The Encoding Standard's §4.2 label table and §9.1 single-byte indexes, from the standard's own
 * machine-readable data. Re-run the generator to update; see its comment for why this is committed.
 *
 * Registry: ${encodings.length} encodings, ${labels.length} labels.
 * Single-byte indexes: ${indexes.length}.
 */
#ifndef ENGINE_HOST_BROWSER_CORE_ENCODING_TABLE_H
#define ENGINE_HOST_BROWSER_CORE_ENCODING_TABLE_H
#include <stdint.h>

/* Every encoding the standard names, whether or not this engine decodes it yet — the LABEL table must answer
   for all of them, because §4.2's "get an encoding" is what decides between an unknown label (a RangeError the
   page sees) and a known encoding this engine has not built (a capability to add). Collapsing the two would
   report a browser-supported encoding as invalid. */
typedef enum {
`;
for (const e of encodings) h += `    ${enumName(e.name)},\n`;
h += `    ENC_COUNT\n} EncodingId;\n\n`;

h += `/* §4.2's LABEL TABLE. Labels are compared after stripping leading/trailing ASCII whitespace and\n` +
     `   ASCII-lowercasing, which is what the standard's "get an encoding" does, so every label here is already\n` +
     `   lowercase and the lookup does the stripping. */\ntypedef struct { const char *label; EncodingId id; } EncodingLabel;\n` +
     `static const EncodingLabel ENCODING_LABELS[] = {\n`;
/* Sorted, so the lookup is a binary search rather than a walk of 228 strcmps per <meta charset>. */
const rows = encodings.flatMap((e) => e.labels.map((l) => [l, enumName(e.name)])).sort((a, b) => (a[0] < b[0] ? -1 : 1));
for (const [l, id] of rows) h += `    { ${JSON.stringify(l)}, ${id} },\n`;
h += `};\n#define ENCODING_LABEL_N ((int)(sizeof ENCODING_LABELS / sizeof ENCODING_LABELS[0]))\n\n`;

h += `/* The NAME each encoding reports through TextDecoder's \`encoding\` attribute — the standard's own name,\n` +
     `   ASCII-lowercased, which is what the attribute returns. */\nstatic const char *const ENCODING_NAMES[ENC_COUNT] = {\n`;
for (const e of encodings) h += `    ${JSON.stringify(e.name.toLowerCase())},\n`;
h += `};\n\n`;

h += `/* §9.1's SINGLE-BYTE INDEXES: byte 0x80..0xFF maps to index[byte - 0x80], and a 0 entry means the byte\n` +
     `   maps to nothing, which is a decoder ERROR rather than U+0000.\n`;
for (const ix of indexes) h += ` * ${ix.name}: ${ix.id}\n`;
h += ` */\n`;
h += `static const uint16_t ENCODING_SINGLE_BYTE[][128] = {\n`;
for (const ix of indexes) {
  h += `    { /* ${ix.name} */\n`;
  for (let i = 0; i < 128; i += 8)
    h += "        " + Array.from(ix.table.slice(i, i + 8)).map((v) => "0x" + v.toString(16).padStart(4, "0")).join(", ") + ",\n";
  h += `    },\n`;
}
h += `};\n\n`;

h += `/* WHICH ROW of the table above an encoding uses, or -1 when it is not single-byte. */\n` +
     `static const signed char ENCODING_SINGLE_BYTE_ROW[ENC_COUNT] = {\n`;
for (const e of encodings) {
  const row = indexes.findIndex((ix) => ix.name === e.name);
  h += `    ${row}, /* ${e.name} */\n`;
}
h += `};\n\n#endif\n`;

writeFileSync(OUT, h);
console.log(`[encgen] ${OUT}: ${encodings.length} encodings, ${rows.length} labels, ${indexes.length} single-byte indexes`);
