/* THE NAMES THE **LANGUAGE** OWNS ON THE GLOBAL OBJECT — the second of the two vocabularies that answer
 * solver/absent.c's question, generated the same way the first one is and for the same reason.
 *
 * absent.c asks, of a global name that resolves nowhere, whether it is a component this engine OWES (absent, so
 * the page's ReferenceError names it) or server-injected app state (unknown input, so the gate forks). Its only
 * suppression is browser/platform_names.h — every name Web IDL exposes on Window — and that table is complete
 * for WEB IDL and empty for ECMASCRIPT. So `Float16Array`, `Atomics`, `Iterator`, `DisposableStack` and every
 * other §19 name a given build does not install fell through to "app state", and a feature-detect on one FORKED
 * where a real browser answers `undefined` and where this engine owes a component.
 *
 * That is the SAME defect absent.c's own header records for the 22-name list that preceded platform_names.h —
 * one vocabulary over. The lesson recorded there is that the set is derived from the standard's own artifact
 * and never typed, so this is derived too: ECMAScript §19 The Global Object states its members as SUBCLAUSES,
 * one per name, and engine/specindex/ecmascript.json is that section index already committed for citegen.mjs.
 * No network, no npm — the corpus is the artifact.
 *
 * THE RULE, STATED SO IT CAN BE CHECKED RATHER THAN TRUSTED: a global property of the language is a DEPTH-2
 * subclause of §19.1 Value Properties, §19.2 Function Properties, §19.3 Constructor Properties or §19.4 Other
 * Properties whose title is an IdentifierName once its parameter list is stripped. A grouping heading is not a
 * name and fails that test ("URI Handling Functions" is the only one, and dropping it is what leaves its four
 * URI functions out — see the residual in solver/absent.c).
 *
 * Run: node engine/esglobalgen.mjs   (writes engine/host/browser/language_names.h) */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ENGINE = dirname(fileURLToPath(import.meta.url));
const INDEX = join(ENGINE, "specindex", "ecmascript.json");
const OUT = join(ENGINE, "host", "browser", "language_names.h");

const idx = JSON.parse(readFileSync(INDEX, "utf8"));
if (idx.key !== "ecmascript")
  throw new Error(`${INDEX} is the index of "${idx.key}", not of ECMAScript`);

/* The clause this derivation is ABOUT, asserted by its own title rather than by its number: a renumber that
   moved §19 would otherwise silently produce a table of something else's subclauses. */
const root = idx.sections["19"];
if (!root || root.title !== "The Global Object")
  throw new Error(`ECMAScript §19 is "${root && root.title}", not "The Global Object" — the corpus has ` +
                  `renumbered and this derivation is reading the wrong clause`);

const CLAUSES = { "1": "Value Properties", "2": "Function Properties",
                  "3": "Constructor Properties", "4": "Other Properties" };
for (const [n, want] of Object.entries(CLAUSES)) {
  const c = idx.sections[`19.${n}`];
  if (!c || !c.title.startsWith(want))
    throw new Error(`ECMAScript §19.${n} is "${c && c.title}", not "${want} of the Global Object"`);
}

const names = new Set();
const dropped = [];
for (const [num, sec] of Object.entries(idx.sections)) {
  const p = num.split(".");
  if (p.length !== 3 || p[0] !== "19" || !(p[1] in CLAUSES)) continue;
  const t = sec.title.replace(/\s*\(.*\)\s*$/, "").trim();
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(t)) names.add(t);
  else dropped.push(`§${num} ${sec.title}`);
}
if (names.size === 0)
  throw new Error("ECMAScript §19 yielded no global names — the index shape has changed");

const sorted = [...names].sort();   /* C strcmp order: every name here is ASCII */
const body = sorted.map((n) => `    ${JSON.stringify(n)},\n`).join("");
writeFileSync(OUT,
`/* GENERATED by engine/esglobalgen.mjs from engine/specindex/ecmascript.json — DO NOT EDIT.
 * Every global property name ECMAScript §19 The Global Object defines: the depth-2 subclauses of §19.1 Value
 * Properties of the Global Object, §19.2 Function Properties of the Global Object, §19.3 Constructor Properties
 * of the Global Object and §19.4 Other Properties of the Global Object. solver/absent.c reads this beside
 * browser/platform_names.h — the two vocabularies that own names on the global object — to tell a component
 * this engine OWES from server-injected app state.
 * Derived from: ${idx.base}
 * Corpus edition: ${idx.specUpdated}
 * Not derived (fails the IdentifierName test, which is what a grouping heading does): ${dropped.join("; ") || "none"} */
#ifndef APICLIENT_LANGUAGE_NAMES_H
#define APICLIENT_LANGUAGE_NAMES_H

static const char *const LANGUAGE_NAMES[] = {
${body}};

#endif
`);
process.stdout.write(`language_names.h: ${sorted.length} name(s) from ${idx.specUpdated}\n`);
if (dropped.length) process.stdout.write(`  not a name: ${dropped.join("; ")}\n`);
