/* GENERATE THE STRONG-DIRECTION TABLE HTML §3.2.6 NEEDS, FROM THE UCD ITSELF.
 *
 * "The first character of bidirectional character type L, AL, or R" appears in four of HTML's directionality
 * algorithms, and answering it requires Bidi_Class — an ENUMERATED Unicode property. Nothing in this tree has
 * it: quickjs's libunicode carries only ECMAScript's binary properties (there is no Bidi_Class among them, and
 * `\p{Bidi_Class=R}` is not a thing a RegExp can ask), and lexbor's unicode module is IDNA normalisation with
 * its own bidi check listed as not implemented. So the data has to come from where a browser's comes from,
 * which is the UCD, and the way libunicode's own tables are made — generated from the file, checked in beside
 * the generator, never hand-typed.
 *
 * WHAT IS EMITTED IS ONLY THE THREE CLASSES THE ALGORITHM ASKS ABOUT. Bidi_Class has 23 values; HTML's
 * question is "is this L, is it AL or R, or is it neither", so a code point's class collapses to three
 * answers and the table holds runs of those. Everything the run table does not cover is NEITHER — which is
 * why the default-L ranges have to be materialized as real runs rather than left to a fallthrough: the UCD's
 * own default for an unlisted code point is L, and treating "not listed" as "not strong" would make every
 * unassigned Latin-range code point invisible to the first-strong scan.
 *
 * THE @missing LINES ARE PART OF THE DATA, not commentary. Unassigned code points inside the RTL blocks are R
 * or AL rather than L, and DerivedBidiClass.txt states that only in its `@missing` comments — a parser that
 * skips comment lines gets Hebrew and Arabic unassigned ranges wrong in the direction that silently reports
 * Arabic text as left-to-right.
 *
 * Run: node engine/gen_bidi_class.mjs <DerivedBidiClass.txt> > engine/host/browser/core/html/bidi_class.h */
import { readFileSync } from 'node:fs';

const MAX = 0x110000;
const NEITHER = 0, L = 1, R = 2, AL = 3;
const NAME = { Left_To_Right: L, Right_To_Left: R, Arabic_Letter: AL };

const src = readFileSync(process.argv[2], 'utf8');
const cls = new Uint8Array(MAX);   // starts NEITHER; the @missing lines fill in the defaults below

/* The @missing lines, IN FILE ORDER: `0000..10FFFF; Left_To_Right` comes first and the RTL blocks override it,
   which is the order the file states them in and the order they have to be applied in. */
for (const m of src.matchAll(/^# @missing: ([0-9A-F]+)\.\.([0-9A-F]+); (\w+)$/gm)) {
  const v = NAME[m[3]];
  if (v === undefined) continue;   // European_Terminator and friends are NEITHER, which is the initial value
  cls.fill(v, parseInt(m[1], 16), parseInt(m[2], 16) + 1);
}
/* …then every EXPLICIT assignment, which overrides the default for the code points that are listed. A listed
   code point whose class is not one of the three is explicitly NEITHER — that is the whole point of listing
   it, since the default it is overriding is L. */
for (const line of src.split('\n')) {
  const m = /^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)/.exec(line);
  if (!m) continue;
  const v = { L, R, AL }[m[3]] ?? NEITHER;
  cls.fill(v, parseInt(m[1], 16), parseInt(m[2] ?? m[1], 16) + 1);
}

const runs = [];
for (let i = 0; i < MAX; ) {
  const v = cls[i];
  let j = i;
  while (j < MAX && cls[j] === v) j++;
  if (v !== NEITHER) runs.push([i, j - 1, v]);
  i = j;
}

const ver = /^# DerivedBidiClass-([\d.]+)\.txt/.exec(src)?.[1] ?? '(unknown)';
const out = [];
out.push(`/* GENERATED by engine/gen_bidi_class.mjs from the Unicode Character Database's DerivedBidiClass.txt,`);
out.push(` * version ${ver}. Do not edit: regenerate.`);
out.push(` *`);
out.push(` * The three Bidi_Class values HTML §3.2.6 asks about — L, R and AL — as sorted, disjoint runs over the`);
out.push(` * whole code point space. A code point in no run is none of the three ("neither"), which is what the`);
out.push(` * first-strong scan skips over. See gen_bidi_class.mjs for why the runs are materialized rather than`);
out.push(` * defaulted. */`);
out.push(`#ifndef ENGINE_HOST_BROWSER_CORE_HTML_BIDI_CLASS_H`);
out.push(`#define ENGINE_HOST_BROWSER_CORE_HTML_BIDI_CLASS_H`);
out.push(``);
out.push(`#include <stdint.h>`);
out.push(``);
out.push(`/* The scan's three answers. BIDI_STRONG_NONE is "not one of L, AL, R" and is what a code point covered`);
out.push(`   by no run is; every algorithm here treats it as a character to keep scanning past. */`);
out.push(`enum { BIDI_STRONG_NONE = 0, BIDI_STRONG_L = 1, BIDI_STRONG_R = 2, BIDI_STRONG_AL = 3 };`);
out.push(``);
out.push(`typedef struct { uint32_t lo, hi; uint8_t strong; } BidiStrongRun;`);
out.push(``);
out.push(`static const BidiStrongRun bidi_strong_runs[] = {`);
for (const [lo, hi, v] of runs)
  out.push(`    { 0x${lo.toString(16).toUpperCase()}, 0x${hi.toString(16).toUpperCase()}, ${v} },`);
out.push(`};`);
out.push(`#define BIDI_STRONG_RUN_COUNT ${runs.length}`);
out.push(``);
out.push(`#endif`);
process.stdout.write(out.join('\n') + '\n');
