/* Web IDL binding generator — the Blink model: bindings' SHAPE is GENERATED from canonical Web IDL, never
 * hand-assembled. Reads the real .idl for each interface we implement (@webref/idl, the W3C-curated source),
 * parses it (webidl2), flattens inherited + mixin members, and emits a C shape table per interface into
 * engine/host/browser/bindings/idl_generated.h. The C components supply only the BEHAVIOR (impl functions,
 * resolved by name in idl_bind); the member LIST, readonly-ness, and operation arity come from the spec, so a
 * member we forgot is an honest opaque/noop and a member we invent that the spec lacks simply never installs. */
import { listAll } from "@webref/idl";
import { parse } from "webidl2";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "host", "browser", "bindings", "idl_generated.h");

// The interfaces our engine implements a binding for. Add an interface here and its real member list is
// generated; the component then resolves impls by member name. (Start small; grow as components convert.)
const INTERFACES = ["AbortSignal", "AbortController"];

const all = await listAll();
// Build a name -> interface/mixin AST node index across ALL specs (so inheritance + includes resolve).
const byName = new Map();
const includes = [];   // { target, includes }
for (const spec of Object.values(all)) {
  let ast;
  try { ast = parse(await spec.text()); } catch { continue; }
  for (const n of ast) {
    if ((n.type === "interface" || n.type === "interface mixin") && n.name) {
      const prev = byName.get(n.name);
      if (prev) prev.members.push(...n.members);   // merge partials
      else byName.set(n.name, n);
    } else if (n.type === "includes") includes.push(n);
  }
}
// Attach mixin members to their host interfaces (interface X includes GlobalEventHandlers).
for (const inc of includes) {
  const host = byName.get(inc.target), mixin = byName.get(inc.includes);
  if (host && mixin) host.members.push(...mixin.members);
}

// Flatten an interface's own + inherited members (walk `inheritance`).
function flatten(name, seen = new Set()) {
  const node = byName.get(name);
  if (!node || seen.has(name)) return [];
  seen.add(name);
  const inherited = node.inheritance ? flatten(node.inheritance, seen) : [];
  return [...inherited, ...node.members];
}

function emit(name) {
  const members = flatten(name);
  const seen = new Set();
  const rows = [];
  for (const m of members) {
    if (m.special === "static") continue;   // static members live on the constructor, not the instance/prototype
    if (m.type === "attribute") {
      if (seen.has(m.name)) continue; seen.add(m.name);
      const ro = m.readonly ? 1 : 0;
      rows.push(`  { "${m.name}", IDL_GEN_ATTR, ${ro}, 0 },`);
    } else if (m.type === "operation" && m.name) {   // named operations only (skip stringifiers/getters)
      const key = "op:" + m.name;
      if (seen.has(key)) continue; seen.add(key);
      const argc = m.arguments.filter((a) => !a.optional && !a.variadic).length;
      rows.push(`  { "${m.name}", IDL_GEN_OP, 0, ${argc} },`);
    }
  }
  return { cname: name.replace(/[^A-Za-z0-9]/g, "_"), rows, count: rows.length };
}

const blocks = INTERFACES.map(emit);
let out = `/* GENERATED by engine/idlgen.mjs from canonical Web IDL (@webref/idl) — DO NOT EDIT.
 * Per-interface member SHAPE (name, kind, readonly, operation arity) straight from the spec. The binding
 * driver (idl_bind) installs these, resolving each member's BEHAVIOR from the component by name. */
#ifndef ENGINE_HOST_BROWSER_BINDINGS_IDL_GENERATED_H
#define ENGINE_HOST_BROWSER_BINDINGS_IDL_GENERATED_H
#include "bindings/idl.h"

`;
for (const b of blocks) {
  out += `static const IdlGenMember ${b.cname}_IDL[] = {\n${b.rows.join("\n")}\n};\n`;
  out += `#define ${b.cname}_IDL_N ${b.count}\n\n`;
}
out += `#endif\n`;
writeFileSync(OUT, out);
console.log(`[idlgen] wrote ${OUT}: ${blocks.map((b) => `${b.cname}(${b.count})`).join(", ")}`);
