/* css-display-3 §1 "Introduction"'s box tree on its child axis: the members whose boxes are the children of
 * one box. It differs from the box's DOM child list in two ways, and every layout and paint walk over a box's
 * children reads this sequence so that the walks agree (core/layout/intrinsic_size.c and core/paint/box_paint.c
 * assert two such agreements).
 *
 * css-display-3 §2.5 "Box Generation: the none and contents keywords" splices a `contents` element: "the
 * element must be treated as if it had been replaced in the element tree by its contents". The sequence pierces
 * `contents` and nothing else; a `none` element is yielded and each walk skips it under its own CSS 2 §9.2
 * arm. The test reads the computed `display`, because box generation runs after the cascade (§1).
 * core/css/css_computed_value.h's `css_box_parent_display` reads the specified value for the same relation
 * because it runs inside the computation of `display` itself.
 * §2.5's Note keeps style on the document tree ("any semantics based on the document tree, such as
 * selector-matching, event handling, and property inheritance, are not affected"), so a walk reading an
 * inherited property of a member reads it off the member's own DOM parent, never off the box it is spliced
 * into. */
#ifndef ENGINE_HOST_BROWSER_CORE_LAYOUT_BOX_TREE_H
#define ENGINE_HOST_BROWSER_CORE_LAYOUT_BOX_TREE_H

#include <stdbool.h>

#include <lexbor/dom/dom.h>
#include <lexbor/css/selectors/pseudo_const.h>   /* one generated enum, no parser */

/* ONE MEMBER: the originating node and the pseudo-element it names, by value. css-pseudo-4 §1 "Introduction":
   "Each pseudo-element is associated with an originating element". `pseudo == __UNDEF` is a source-document
   node; `_MARKER` is css-lists-3 §3.1 "The ::marker Pseudo-Element"'s box, which is "generated by the ::marker
   pseudo-element of a list item as the list item’s first child, before the ::before pseudo-element (if it
   exists on the element)". It is yielded exactly when core/layout/list_marker.h's `list_marker_box_generated`
   answers TRUE. ::before and ::after yield nothing: css-pseudo-4 §4.1 generates them only "When their computed
   content value is not none", and `content` does not parse in this engine.
   A pseudo member is not a DOM node because a node in the sibling chain is one the page's `childNodes` reads,
   and a node outside it ends core/layout/box_tree.c's forward step. `node == NULL` is the end of a sequence. */
typedef struct {
    lxb_dom_node_t *node;
    lxb_css_selector_pseudo_element_id_t pseudo;
} BoxTreeChild;

/* The source-document member `n`, or the end of a sequence for NULL. */
static inline BoxTreeChild box_tree_child_of_node(lxb_dom_node_t *n)
{
    BoxTreeChild c = { n, LXB_CSS_SELECTOR_PSEUDO_ELEMENT__UNDEF };

    return c;
}

static inline bool box_tree_child_exists(BoxTreeChild c) { return c.node != NULL; }

static inline bool box_tree_child_is_pseudo(BoxTreeChild c)
{
    return c.pseudo != LXB_CSS_SELECTOR_PSEUDO_ELEMENT__UNDEF;
}

/* Is `c` the source-document member `n`? FALSE for a pseudo member whose originating node is `n`. */
static inline bool box_tree_child_is_node(BoxTreeChild c, const lxb_dom_node_t *n)
{
    return c.node == n && !box_tree_child_is_pseudo(c);
}

static inline bool box_tree_child_same(BoxTreeChild a, BoxTreeChild b)
{
    return a.node == b.node && a.pseudo == b.pseudo;
}

/* THE NODE OF A MEMBER THE CALLING WALK CAN ONLY MEET AS A SOURCE-DOCUMENT NODE — a walk whose container
   generates no pseudo-element box, or one that has already taken its pseudo-member arm. Asserts that, naming
   the calling site; the end of a sequence answers NULL. */
lxb_dom_node_t *box_tree_child_node_at(BoxTreeChild c, const char *file, int line);
#define box_tree_child_node(c) box_tree_child_node_at((c), __FILE__, __LINE__)

/* THE FIRST MEMBER of `box`'s sequence: its ::marker where `list_marker_box_generated(box)`, otherwise its first
   source-document member; the end where it has none. `box` must generate a box — a `contents` element's
   children are in its box parent's sequence. Seed a loop with it and step with the entry below; the sequence
   is two steps and not a list, so no walk allocates. */
BoxTreeChild box_tree_first_child(lxb_dom_element_t *box);

/* THE MEMBER AFTER `child`, or the end. `child` must be a member of `box`'s sequence — `box_tree_parent(child)
   == box` — which is asserted, since a walk half-converted from `->next` would hand it a node of another
   box's sequence and be answered plausibly. */
BoxTreeChild box_tree_next_sibling(lxb_dom_element_t *box, BoxTreeChild child);

/* THE MEMBER BEFORE `child`, or the end at the head; the same membership requirement. It is the forward step's
   inverse and both halves are asserted: `box_tree_next_sibling(box, prev) == child` where there is a
   predecessor, and `box_tree_first_child(box) == child` where there is none. css-flexbox-1 §4 "Flex Items"'
   maximal text sequence and core/layout/block_flow.h's `BlockFlowRun` bounds are the callers. */
BoxTreeChild box_tree_prev_sibling(lxb_dom_element_t *box, BoxTreeChild child);

/* THE BOX `n`'s BOXES ARE CHILDREN OF. For a pseudo member it is the originating element itself. For a source
   node it is the nearest ancestor element that generates a box — the DOM parent unless a chain of `contents`
   elements stands between — or NULL where the ascent leaves the element tree. css-display-3 §2.8 "The Root
   Element's Principal Box" ("a display of contents computes to block on the root element") is why the ascent
   ends at the root. Unlike its two siblings it answers for a spliced `n`, because a spliced element's box
   parent is exactly the box its contents are spliced into. */
lxb_dom_element_t *box_tree_parent(BoxTreeChild n);

#endif
