/* GENERATED BY engine/gen_line_break.mjs from the Unicode Character Database 17.0.0 — DO NOT EDIT.
   Re-run the generator instead; its header carries the four curl commands that obtain the input, the
   sha256 each is pinned to, and why the rules need four files rather than one.

   The DECLARATIONS. The data is in core/layout/line_break_class.c.

   [UAX14] Unicode Line Breaking Algorithm's Line_Break property, AFTER §6.1 rule LB1's resolution of AI,
   SA, SG, XX and CJ — see the generator for why that resolution is a generation-time fact for this engine,
   and core/layout/text_run.c's `tr_require_no_line_break_tailoring` for the assert that fires the day it
   stops being one. CB is NOT resolved here: LB20 "Break before and after unresolved CB" is its own default
   and is a rule. */
#ifndef ENGINE_HOST_BROWSER_CORE_LAYOUT_LINE_BREAK_CLASS_H
#define ENGINE_HOST_BROWSER_CORE_LAYOUT_LINE_BREAK_CLASS_H

#include <stdint.h>

/* The 44 Line_Break values that survive LB1. There is deliberately no constant for AI, SA, SG, XX or
   CJ: a rule cannot name a class the resolution above has already removed. */
typedef enum {
    LB_CLASS_AK = 0,
    LB_CLASS_AL = 1,
    LB_CLASS_AP = 2,
    LB_CLASS_AS = 3,
    LB_CLASS_B2 = 4,
    LB_CLASS_BA = 5,
    LB_CLASS_BB = 6,
    LB_CLASS_BK = 7,
    LB_CLASS_CB = 8,
    LB_CLASS_CL = 9,
    LB_CLASS_CM = 10,
    LB_CLASS_CP = 11,
    LB_CLASS_CR = 12,
    LB_CLASS_EB = 13,
    LB_CLASS_EM = 14,
    LB_CLASS_EX = 15,
    LB_CLASS_GL = 16,
    LB_CLASS_H2 = 17,
    LB_CLASS_H3 = 18,
    LB_CLASS_HH = 19,
    LB_CLASS_HL = 20,
    LB_CLASS_HY = 21,
    LB_CLASS_ID = 22,
    LB_CLASS_IN = 23,
    LB_CLASS_IS = 24,
    LB_CLASS_JL = 25,
    LB_CLASS_JT = 26,
    LB_CLASS_JV = 27,
    LB_CLASS_LF = 28,
    LB_CLASS_NL = 29,
    LB_CLASS_NS = 30,
    LB_CLASS_NU = 31,
    LB_CLASS_OP = 32,
    LB_CLASS_PO = 33,
    LB_CLASS_PR = 34,
    LB_CLASS_QU = 35,
    LB_CLASS_RI = 36,
    LB_CLASS_SP = 37,
    LB_CLASS_SY = 38,
    LB_CLASS_VF = 39,
    LB_CLASS_VI = 40,
    LB_CLASS_WJ = 41,
    LB_CLASS_ZW = 42,
    LB_CLASS_ZWJ = 43,
} LineBreakClass;
#define LINE_BREAK_CLASS_COUNT 44

/* The classes as runs that PARTITION the code point space: run i covers
   (i ? line_break_class_run_end[i - 1] + 1 : 0) .. line_break_class_run_end[i], so every code point is in
   exactly one and a search over them cannot miss. LineBreak.txt's own `@missing: 0000..10FFFF; XX` is
   materialized as part of that rather than left to a fallthrough in the consumer, which is where a second
   copy of LB1's resolution would otherwise live. */
#define LINE_BREAK_CLASS_RUN_COUNT 2622
extern const uint32_t line_break_class_run_end[LINE_BREAK_CLASS_RUN_COUNT];
extern const uint8_t line_break_class_run[LINE_BREAK_CLASS_RUN_COUNT];

/* THE FOUR SETS UAX14 NAMES A SECOND UNICODE PROPERTY FOR, each already intersected with the Line_Break
   class its rule asks about — so the consumer never needs the second property in general, only where a
   rule quotes it. Sorted, disjoint, inclusive. */
typedef struct { uint32_t lo, hi; } LineBreakRange;

/* LB15a's and LB19's `[\p{Pi}&QU]` — General_Category Initial_Punctuation. */
#define LINE_BREAK_QU_INITIAL_COUNT 11
extern const LineBreakRange line_break_qu_initial[LINE_BREAK_QU_INITIAL_COUNT];

/* LB15b's and LB19's `[\p{Pf}&QU]` — General_Category Final_Punctuation. */
#define LINE_BREAK_QU_FINAL_COUNT 10
extern const LineBreakRange line_break_qu_final[LINE_BREAK_QU_FINAL_COUNT];

/* LB19a's and LB30's `$EastAsian` — East_Asian_Width Fullwidth, Wide or Halfwidth. NOT intersected with
   a class: LB19a asks it of the character on the OTHER side of a QU, which is any class at all. */
#define LINE_BREAK_EAST_ASIAN_COUNT 129
extern const LineBreakRange line_break_east_asian[LINE_BREAK_EAST_ASIAN_COUNT];

/* LB30b's `[\p{Extended_Pictographic}&\p{Cn}]` — the code points reserved for future emoji. */
#define LINE_BREAK_UNASSIGNED_PICTOGRAPHIC_COUNT 36
extern const LineBreakRange line_break_unassigned_pictographic[LINE_BREAK_UNASSIGNED_PICTOGRAPHIC_COUNT];

/* LB28a writes U+25CC DOTTED CIRCLE into its rules as a literal: "the class [◌] contains the single
   character U+25CC DOTTED CIRCLE". */
#define LINE_BREAK_DOTTED_CIRCLE 0x25CC

#endif
