/* THE PLATFORM-GLOBAL NAME LIST, DERIVED ONCE.
 *
 * `engine/host/browser/platform_names.h` is generated by `engine/idlgen.mjs` from `@webref/idl`, so it is the
 * artifact that already states what Web IDL exposes on Window. Two instruments read it — `probe_globals.mjs`
 * asks a real realm which of those names it answers, and `rank_globals.mjs` asks frozen bundles which of them
 * real code reaches for — and a parse written twice is the second copy of a fact, which is the copy that
 * drifts. CLAUDE.md §an-auditor-derives-the-rule-it-checks is the reason this is a module and not a paragraph
 * repeated in each caller: the day the generator's shape changes, ONE reader fails loudly rather than one
 * failing and the other silently measuring a subset. A probe that silently measures a subset reports a
 * smaller absence and reads as progress.
 *
 * IT FAILS LOUD RATHER THAN RETURNING SHORT. The table is bounded by its own declaration and by the brace
 * that closes it, anchored on BOTH, so a second array added to that header later cannot silently extend this
 * list. An empty parse throws. There is no expected count here and there must not be: a count of the platform
 * surface rots, and the reader wants today's. */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

export const PLATFORM_NAMES_HEADER =
    join(dirname(fileURLToPath(import.meta.url)), "..", "engine/host/browser/platform_names.h");

export function platformNames(header = PLATFORM_NAMES_HEADER) {
    const src = readFileSync(header, "utf8");
    const open = src.indexOf("PLATFORM_NAMES[] = {");
    if (open < 0) throw new Error(`${header}: no PLATFORM_NAMES[] table — the generator's shape changed`);
    const close = src.indexOf("};", open);
    if (close < 0) throw new Error(`${header}: PLATFORM_NAMES[] is unterminated`);
    const names = [...src.slice(open, close).matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((m) => m[1]);
    if (names.length === 0) throw new Error(`${header}: PLATFORM_NAMES[] parsed empty`);
    return names;
}
