/* THE ABSENT-GLOBALS PROBE — what fraction of the platform's own global names this engine does not answer.
 *
 * WHY THIS IS A COMMITTED INSTRUMENT AND NOT A SCRATCH FILE. It was written as one, its measurement was
 * quoted for a whole session, and it was never in the repository — so a lane sent to re-run it re-phrased
 * its search three ways and correctly reported that no such probe exists. A number whose instrument nobody
 * can run is a number belonging to nothing, and the summary that carried it read exactly like a record.
 * CLAUDE.md's cure for a count is to hand over the DERIVATION AS A COMMAND rather than the figure; a command
 * that lives only in a container's scratch directory is not one. So this file prints NO expected total and
 * NO expected absence count: both rot, both shrink as the work is done, and the reader wants today's.
 *
 * THE NAME LIST IS DERIVED, NEVER COPIED. `engine/host/browser/platform_names.h` is generated by
 * `engine/idlgen.mjs` from `@webref/idl`, so it is the artifact that already states what Web IDL exposes on
 * Window. An embedded copy of those names is the second copy of a fact, and the copy nobody regenerates is
 * the one that drifts — the same reason `idlgen` reads the real `.idl` instead of a table somebody typed.
 * This reads the header. If the header's shape changes, this fails loudly rather than emitting a short list:
 * a probe that silently measures a subset reports a smaller absence and reads as progress.
 *
 * WHAT IT MEASURES, EXACTLY, AND WHAT IT DOES NOT. `name in globalThis` asked in a real realm of the running
 * engine. That is the ENGINE's answer, which is the point: a member-list audit walks the components it can
 * find and is blind in BOTH directions at its edges — a wholly absent interface contributes ZERO rows to it
 * (and is the loudest failure a page can hit, a ReferenceError on the first line naming it), while a member
 * another layer installs reads as absent to it though a page reaches it perfectly well. Asking the realm has
 * neither edge. It says nothing whatever about what a present member ACCEPTS, or whether its property
 * attributes match Web IDL §3.7 — those are different axes with different instruments.
 *
 * USAGE
 *   node testing/probe_globals.mjs > <somewhere>/probe_globals.html
 * then load that document through the harness against the built artifact, and read the PROBE- lines. Quote
 * the result with the artifact's stamped revision beside it (`extension/lib/qjs/qjs.mjs.build.json`), and
 * with the run count and spread — a single run of anything is not a measurement. */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const header = join(root, "engine/host/browser/platform_names.h");
const src = readFileSync(header, "utf8");

/* The table is the ONE array in that header, and it is bounded by its own declaration and the brace that
 * closes it — anchored on both, so a second array added later cannot silently extend this list. */
const open = src.indexOf("PLATFORM_NAMES[] = {");
if (open < 0) throw new Error(`${header}: no PLATFORM_NAMES[] table — the generator's shape changed`);
const close = src.indexOf("};", open);
if (close < 0) throw new Error(`${header}: PLATFORM_NAMES[] is unterminated`);

const names = [...src.slice(open, close).matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((m) => m[1]);
if (names.length === 0) throw new Error(`${header}: PLATFORM_NAMES[] parsed empty`);

/* The document asks with `in` rather than reading the value, because a member whose getter THROWS is still
 * present, and a member answering `undefined` may be a real own property. `in` is the question §3.7's
 * descriptor actually settles. It is asked of `this` at top level, which is the global object itself —
 * globalThis may legitimately be one of the names under test. */
const doc = `<!doctype html><meta charset="utf-8"><title>absent-globals probe</title><script>
var NAMES=${JSON.stringify(names)};
var G=this, absent=[];
for(var i=0;i<NAMES.length;i++){ if(!(NAMES[i] in G)) absent.push(NAMES[i]); }
console.log("PROBE-TOTAL "+NAMES.length);
console.log("PROBE-ABSENT "+absent.length);
for(var j=0;j<absent.length;j+=30) console.log("PROBE-NAMES "+absent.slice(j,j+30).join(" "));
console.log("PROBE-END");
</script>`;

process.stdout.write(doc);
