/* ABSENT STATE — which read of a name the page cannot resolve is unknown INPUT, and which is a component this
 * engine owes. Two bases ask it: the GLOBAL OBJECT, and a RECORD THE DOCUMENT PUBLISHED onto it. */
#ifndef ENGINE_HOST_SOLVER_ABSENT_H
#define ENGINE_HOST_SOLVER_ABSENT_H
#include "quickjs.h"

/* Install as JSConcolicHooks.absent. `obj` is the base the read missed on — the global object, or a published
   record (the engine has already established it is one of the two). */
JSValue absent_read_hook(JSContext *ctx, JSValueConst obj, JSAtom name);

/* Install as JSConcolicHooks.present — THE SAME QUESTION FOR A MEMBER THE RECORD HOLDS. A published record's
   extent was chosen against THIS visitor's credentials, so `__FLAGS.admin === false` is a fact about this
   session and not about the program: it is unknown for control flow exactly as a missing member is, and it
   additionally KNOWS what it concretely is. So this mints the same derivation the read hook does, with the
   held value as the EXAMPLE — which is the whole of §solver's "a loaded `features.admin:false` must NOT
   concretize the gate" in one call. `holder` is the record the slot was found on and `value` is borrowed. */
JSValue absent_present_hook(JSContext *ctx, JSValueConst holder, JSAtom name, JSValueConst value);

/* Install as JSConcolicHooks.publish. The engine has found `value` reachable from the global object through
   records the document's own inline scripts built, and states the PARENT it hangs off and the NAME it hangs
   under; this files the PATH the record's members are then read by. Parents arrive before their children, so
   a child's path is composed from a parent already filed — a child whose parent is not filed is the engine
   and this file disagreeing about what is published, which crashes rather than inventing a root. */
void absent_publish_hook(JSContext *ctx, JSValueConst parent, JSAtom name, JSValueConst value);

/* Give back the published-namespace registry. Called on the agent's release column, beside the source
   registry: a path names a record of a document that is gone. */
void absent_free(void);

/* WHICH OF THE TWO STANDARDS OWNS A GLOBAL NAME. `ABSENT_VOCAB_N` is the COUNT and is never a vocabulary; it
   is what a per-vocabulary array is sized by, so a third standard putting names on the global object (the `Intl`
   residual in absent.c) adds a row to one array rather than a second counter beside it. */
typedef enum { ABSENT_VOCAB_WEBIDL, ABSENT_VOCAB_ECMASCRIPT, ABSENT_VOCAB_N } AbsentVocab;

/* WHICH STANDARD OWNS THIS GLOBAL NAME, AND THE TABLE'S OWN SPELLING OF IT. Answered from the two generated
   vocabularies — browser/platform_names.h, every name Web IDL exposes on Window, generated by
   engine/idlgen.mjs; and browser/language_names.h, ECMAScript §19 The Global Object's own subclauses,
   generated by engine/esglobalgen.mjs — never from anything a component or a person declares.

   TWO TABLES AND ONE ENTRY POINT, WHICH IS THE ARGUMENT THE TWO PREDICATES HERE CARRIED AND STRICTLY MORE OF
   IT. That argument is kept rather than retired: "which standard owns a name is a fact a `@WHY` has to be
   able to state, and a MERGED TABLE is one bit answering two questions the day the two disagree." The tables
   are still two, they are still searched separately, and neither is merged into the other. What changed is
   that the ANSWER STATES which of them held the name, instead of a caller asking twice and having to remember
   which of the two calls said yes — so the fact that argument is about is now CARRIED, which is the same rule
   §AN-ASSERT-THAT-NAMES-A-REMEDY makes about a site travelling with its operation.

   THE ENTRY IS THE TABLE'S OWN STATIC STRING, so it outlives every document and a caller may key on the
   POINTER: two reads of one name yield one pointer, and a page cannot get its own bytes into anything keyed
   that way — which is what lets absent_json write its row names with no escaping pass over page-supplied
   input, and what makes its "these are MY bytes" assert a statement about a generated table rather than about
   a document.

   Returns NULL when neither standard owns the name, and `*vocab` is then untouched. */
const char *absent_standard_name(const char *name, AbsentVocab *vocab);

/* THE NAMES THIS DOCUMENT ASKED FOR AND THIS ENGINE DID NOT ANSWER — solver/result.c's `_absent`, as one JSON
   object on the heap (caller frees; NULL only on allocation failure, which every composer on that seam treats
   as "this census is absent" rather than as a reason to fail a run). The composer in absent.c states the
   population, the denominator every number in it is a fraction of, the KIND of every row, the identity they
   close over, and the two spellings of a feature detect this census structurally cannot see. */
char *absent_json(void);

#endif
