/* THE COLD TIER — RAM holds the hot working set; the lowest-value SUSPENDED flows page out and resume on
 * demand, byte-identically. See CLAUDE.md §Time-travel-resume ("the cold low-value tail serializes to IDB as
 * suspended snapshots and resumes on demand"), §scheduler ("STARVE means deprioritize-and-page, NEVER
 * terminate"; "an engine self-parks its residue to the IDB cold tier under pressure") and engine.c's own
 * flow-compile OOM, which names this file as what carries past the RAM floor.
 *
 * ITS FIRST CONTRACT IS THE CENSUS, and that ordering was not a preamble to the work — it decided the work.
 * A pager cannot be written for a snapshot nobody can describe: what crosses the boundary decides the encoder,
 * and what is SHARED between siblings decides whether writing one flow's snapshot writes its siblings' too.
 * Both questions were answered by the numbers below and both answers are now load-bearing in the RECIPE (the
 * second contract, further down): the shared chains are what the park writes ONCE and names by ordinal, and
 * the per-flow rows are what a replay regenerates instead of writing at all. The two chains that already report themselves (cow.c's `heapSegs`, dom_cow.c's `domSegs`) say
 * the sharing works — they were flat at 14/727 and 18/5160 across 14003 flows — and everything else in a
 * snapshot had no number at all. This is that number, per part, so a part that turns out to be a per-flow COPY
 * of state its parent already holds is visible as one instead of being paged out N times.
 *
 * WHAT A SNAPSHOT IS, in the order §Time-travel-resume names it: the flow's per-flow COW delta (its heap AND
 * DOM writes) plus its suspended heap-frame chain, plus the rest of what the scheduler swaps with it — the
 * decision vector and its cursor, the path constraint, the queued jobs, the replies the host still owes, and
 * the flow's own byte state (its lazily-loaded chunk bodies, its candidate substitution, a routed record).
 * Each of those is a row here, and each row is either PER-FLOW or SHARED; the pair is the whole design
 * question, so the census answers it directly rather than reporting one total. */
#ifndef ENGINE_HOST_SOLVER_COLD_H
#define ENGINE_HOST_SOLVER_COLD_H

#include "quickjs.h"
#include "solver/flow.h"   /* the park's unit is ONE member of the frontier */

/* WHAT THE FRONTIER'S SNAPSHOTS ARE MADE OF. Every `*_bytes` is host `malloc` unless the row says otherwise:
   the runtime's own allocations (the frame chains, the step machines) are counted by quickjs and reported in
   the @HEAP line's `unattributed` residual, which is named here rather than restated. */
typedef struct {
    long flows;              /* live members of the frontier */
    /* … suspended inside a live heap-frame chain. This said "the part with no encoder yet", which was the
       right thing to record before there was a recipe and is the wrong thing to leave standing now: the frame
       chain is not encoded and is not OWED an encoder — it is REGENERATED by replaying the flow's arms, which
       is what makes a recipe immune to the stale-stage-index failure a serialized rest point would have. What
       the number is FOR is the park's cost: a framed flow is one whose resume has to re-execute the document
       to get back where it was, so this is how much of the frontier pays that. */
    long framed;
    long blocked;            /* … holding an unanswered host request */

    /* WHY THE MEMBERS ARE NOT FINISHING — one count per arm of flow_step, over the whole frontier. It is the
       row `finished`/`live` could never carry: those two say work is being ADMITTED and not RETIRED, and this
       says what the members that are not retiring are DOING, which is the difference between four different
       diffs (solver/step_unit.h names them). It is a PARTITION and not a selection — every live member is in
       exactly one bucket, so the counts sum to `flows` and that identity is what says the walk saw everybody.
       PER-FLOW BECAUSE THE QUESTION IS PER-FLOW. The scheduler's own `g_step_unit` is the LAST step ANY flow
       took, which answers about the instant the census was taken and not about the frontier; the flow carries
       its own (solver/flow.h) and this counts them. */
    long step_units[STEP_UNIT_N];

    /* WHERE IN ITS DOCUMENT EACH MEMBER IS STANDING — one count per CURSOR VALUE, over the whole frontier.
       Emitted as `programCursors`.

       A CURSOR IS NOT A PROGRAM INDEX, AND THIS BLOCK CALLED IT ONE. solver/flow.h's `script_i` runs over
       [0, dyn_n] — CLOSED at the top, because `dyn_n` is what the cursor holds between two programs at the
       tail — while a PROGRAM index runs over [0, dyn_n) and is the domain solver/engine.h's `deepest` and
       `completed` live in. The histogram is therefore ONE BUCKET WIDER than the document has programs, and its
       top bucket is the members that have run out of rows. Read as a program index that bucket names a program
       the document does not have, which is how the row a reader is told to compare against `deepest` came to
       look like an instrument contradicting the maximum beside it. It is not: on a document of eleven programs,
       `deepest 10 / completed 10` and a bucket at 11 are the SAME statement made twice.
       THE IDENTITY THAT SAYS SO IS ASSERTED, at solver/result.c where this census and the frontier census are
       in one hand: every live member's cursor is at most `deepest + 1`. A cursor of `c` above zero means the
       member left the program at `c - 1`, and a program is only left after engine.c has STARTED it at the one
       line that raises `deepest` — so `deepest >= c - 1` for every standing member, and a width above
       `deepest + 2` is the two rows describing different runs.

       IT IS THE ROW `deepest` AND `completed` STRUCTURALLY CANNOT CARRY, and those two are otherwise the whole
       of what this engine says about a frontier's progress THROUGH its programs. Both are GLOBAL MAXIMA over
       the document (solver/engine.h), so each is set by whichever single member got furthest and neither says
       anything whatever about where the others are: `deepest 11` is exactly as true of a frontier holding ONE
       member at 11 and two thousand at 3 as it is of one whose EVERY member is at 11. Those are OPPOSITE
       DIAGNOSES — the first is a frontier whose mass never advances while a few members run deep, which is a
       claim about what the pick prefers; the second is BFS behaving precisely as designed on a page that
       forks, where the work is simply unbounded and there is nothing to fix. A maximum cannot separate them at
       ANY value, so no reading composed from those two rows has ever been able to state which of the two a run
       was in — and the stall question has accordingly been answered three different ways.

       IT IS THE MEMBERS' OWN CURSOR (solver/flow.h's `script_i`), which is the position each flow stands at in
       its ONE program sequence. `framed` above is what says how many of them are INSIDE the program at that
       position rather than between two, so the pair is a POSITION and a PHASE and neither is derivable from
       the other.

       ITS EXTENT IS DERIVED FROM THE POPULATION AND NOT FROM A LIST, which is the one way its shape differs
       from `step_units` beside it and is why it carries its own length instead of being a fixed array. The row
       set is [0, the highest cursor any LIVE member stands at], DENSE — every index in it emitted, zeroes
       included — because THE ZEROES ARE THE SIGNAL: "two thousand at 3, nothing between 4 and 10, one at 11"
       is the entire reading, and a sparse table renders that as the same bytes as a frontier that never
       reached 4. The width is therefore a function of the DOCUMENT's program depth and never of the frontier's
       size, however many members are standing.

       A PARTITION, exactly as `step_units` is: every live member stands at exactly one cursor, so these counts
       SUM to `flows`, and that identity is what says the walk saw everybody. The row set is never EMPTY
       either — cold.c gives it program 0 on an empty frontier, which is a position every document's sequence
       has and every flow starts at, so `{"0":0}` is the true count of the members standing there rather than a
       fabricated row, and `{}` (which every reader of this census refuses by name) never reaches one.

       AND IT IS A REPORT AND NEVER A BOUND (§NO BOUNDS). Nothing in the engine reads it to decide anything: no
       fixpoint over a bucket that stopped moving, no cap on how deep a member may stand, no seen-set over
       cursors, no refusal of a run whose mass sits low. A per-index distribution over the frontier is exactly
       the shape someone reaches for when they want a no-progress detector, which is why that is said here as
       well as at the walk — this is an instrument, and the verdict it informs is a person's. */
    long *program_cursors;
    int   program_cursor_n;
    /* …AND HOW MANY OF THE STANDING MEMBERS HAVE NO ROW LEFT TO RUN — `script_i == dyn_n`, counted on the same
       walk. Emitted as `outOfPrograms`.

       IT IS NOT DERIVABLE FROM THE HISTOGRAM AND THAT IS THE WHOLE REASON IT IS A ROW. The bucket a member
       lands in is its cursor, and one cursor value covers two states that take opposite work: INSIDE the
       program at that index (its frame is live) and PAST THE LAST ROW OF ITS OWN SEQUENCE (there is no program
       there to be inside). `framed` above separates those two — but `framed` is a count over the WHOLE
       frontier and cannot be attributed to a bucket, and `dyn_n` is per-flow and crosses no boundary at all,
       so nothing a reader holds can tell the two apart. Two members in one bucket, and no way to say which is
       which.
       WHAT TURNS ON IT IS THE ORPHAN QUESTION, which is why this is the fact worth carrying rather than a
       per-bucket phase table. engine.c reaches engine_orphan_seed where a flow has no program, job, delivery,
       checkpoint or lifecycle stage DUE at the current moment — the last rung before the clock may move — so
       `0` orphan asks has two readings — no member has run out of PROGRAMS, or members have and are held by
       one of the other four — and the census reported them identically. (That list used to end "timer,
       rendering opportunity, outstanding reply or unmodelled close request", which was the seat the seed had
       at the ladder's EXIT. Those three sit BELOW the two clock-driven sources and a rendering opportunity is
       generated for ever on a document that has one, so that seat was reached only where the opportunity did
       NOT fire and the reading it named was the wrong one to hold — which is why the numbers below were
       measured against a row whose movement was a fact about the document rather than about the frontier.)
       Measured on the native smoke fixture: 129 members standing at
       the top bucket with `deepest 10`, i.e. every program the document has, against a run reporting zero
       orphan asks. Those two together are the second reading and say which of the four to open; either one
       alone is the first.
       A REPORT AND NEVER A BOUND (§NO BOUNDS), for `program_cursors`' reason exactly: nothing in the engine
       reads it, no arm of any verdict branches on it, and "how many members have run out of programs" is
       precisely the shape a drain check would be built from. */
    long  out_of_programs;

    /* PER-FLOW rows — these multiply by the number of parked flows, so they are what a pager pays for. */
    long dec_entries;        /* decision-vector slots the flows STAND ON — a chain total, so this counts the
                                same shared prefix once per flow that references it and is deliberately NOT a
                                byte figure. It is the number that was quadratic when the vector was copied. */
    long dec_bytes;          /* …and what the flows themselves own for it: one blob header each. There is no
                                second row for a BIRTH vector any more: the flat per-flow array a from-baseline
                                flow used to be able to carry is deleted, and a flow that stands on a recorded
                                path — forked or resumed from the cold tier — stands on the shared chain. */
    long head_entries;       /* heap COW delta HEADS (the writes each flow has made since its last fork) */
    long head_bytes;
    long dom_head_entries;   /* the DOM half of the same */
    long dom_head_bytes;
    long job_count;          /* queued microtasks/tasks */
    /* EVERY REGISTER'S LENGTH, SUMMED — a FOOTPRINT and not a debt, which is what this line used to call it
       and what `build.mjs` used to render it as ("N owed repl(ies)"). It counts every entry of every live
       flow's register whatever state it is in: outstanding, ALREADY ANSWERED (a flow keeps an answered entry
       until IT delivers), declined, and synchronous. On the wasm smoke at 74eb1d62 it read 299306 beside
       `owed: 0` and `blocked: 0` in the same census, which as rendered was a flat contradiction and in fact
       was not one — every one of those entries had been answered and none delivered. A reader reasoned from
       it as a debt and reported the host was never asked.
       IT IS PAIRED WITH `pend_bytes` AND THAT IS ITS JOB: the two are one row of the per-flow memory census,
       so a rising count beside a rising KiB is what says the registers are where the frontier's memory is.
       THE DEBT IS A DIFFERENT NUMBER AND IT ALREADY HAS A FUNCTION — `pending_owed_replies` (solver/pending.h)
       — and the RATE that says whether the debt is being paid is `pending_index_asked_total` against
       `pending_index_answered_total`, which is what the census publishes as `replyAsked`/`replyAnswered`. */
    long pend_count;
    long pend_bytes;
    /* HOW MANY MEMBERS COULD TAKE A REPLY AT ALL, AND HOW MANY ACTUALLY HAVE ONE TO TAKE — the reply-delivery
     * arm's own guard, counted in MEMBERS, beside the two rows above that are counted in ENTRIES. Emitted as
     * `stackEmpty` and `canDeliver`.
     *
     * WHY A DEBT IN ENTRIES CANNOT ANSWER IT. `pend_ready` below is the deliverable population summed over
     * every register, and a run in which it equals `pend_count` exactly, census after census, says every entry
     * the frontier holds has been answered and none delivered. What it CANNOT say is why, and the two
     * candidates take opposite work: the arm is being reached and consuming one entry at a time against a debt
     * that forks faster than it drains, or the arm is not being reached at all because its guard is false for
     * nearly every member. Those differ in what to fix — the drain's granularity, or whatever is upstream of a
     * flow ever reaching an empty stack — and no row of this census separated them.
     *
     * AND `framed` IS NOT THIS NUMBER, WHICH IS THE PART THAT LOOKS DERIVABLE AND IS NOT. The guard is
     * flow_stack_empty (solver/flow.h), and that is a CONJUNCTION: no live frame, AND the row at the cursor is
     * not a DYN_POS_IMMEDIATE one — §4.12.1.1 "Processing model"'s "immediately execute the script element",
     * which runs INSIDE the program that inserted it and so does not empty the stack either. `framed` answers
     * the first half only, so `flows - framed` is an UPPER BOUND on `stack_empty` and a reader who takes it for
     * the count is reading a different question's answer. That is why this is asked through the predicate the
     * arm itself is guarded on rather than recomputed here.
     *
     * `can_deliver` IS THE WHOLE GUARD — stack-empty AND holding a deliverable entry — so it is a subset of
     * `stack_empty` by construction, which result.c asserts. It is the number that decides the question above:
     * `can_deliver` at 0 across a run whose `pend_ready` is in the hundreds of thousands says the debt is held
     * entirely by members that cannot take it, and the drain is not where the defect is.
     *
     * A REPORT AND NEVER A BOUND (§NO BOUNDS), for `program_cursors`' reason exactly: nothing in the engine
     * reads either, and "how many members can make progress" is precisely the shape a no-progress detector
     * would be built from. */
    long stack_empty;
    long can_deliver;
    /* …AND THE ONE POPULATION INSIDE THAT LENGTH THAT IS A DEBT THE FRONTIER OWES ITSELF: entries the host has
       ANSWERED which the flow naming them has not yet delivered (solver/pending.h's pending_deliverable_count).
       IT IS THE DENOMINATOR OF `deliver-one-reply` AND NOTHING ELSE IN THIS CENSUS IS. That arm consumes exactly
       one NAMING per visit; `replyAsked`/`replyAnswered` count RECORDS, and one record is named by every register
       that forked while it was in flight — so the reply door's rate can be `asked == answered` while this number
       climbs without bound, and the two must never be divided by one another. A flow cannot reach flow_step's
       FINISHED arm while this is non-zero for its register (the delivery rung returns first), and a flow that
       does not finish never releases its register, so a rising `pend_ready` beside `finished 0` is one fact and
       not two. A REPORT AND NEVER A BOUND (§NO BOUNDS): nothing reads it, no arm branches on it. */
    long pend_ready;
    long misc_bytes;         /* the Flow struct, its candidate substitution, a routed record, the blob headers */

    /* SHARED rows — counted ONCE for the whole frontier, because a frozen segment is referenced by every flow
       that forked below it. A pager that wrote these per flow would multiply the sharing back out. */
    /* THE PROGRAM TEXT THIS INSTANCE HOLDS, AND HOW MANY PROGRAMS THAT IS. It was a PER-FLOW row summing
       `strlen` over each flow's rows, which was the honest number while each flow strdup'd its own copy of
       every program it held; the bodies are shared now (solver/dyn_body.h), so summing them per flow would
       report the sharing as if it did not exist — the mistake this block's own sentence names. The count
       beside the bytes is what says whether a growing number is more programs or bigger ones. */
    long dyn_bytes, dyn_count;
    /* THE TWO HEAP/DOM CHAINS CONTRIBUTE ONLY THEIR BYTES, and the count and entry rows that stood beside them
       are DELETED rather than left unread. They were a second copy of `heapSegs`/`heapSegEntries` and
       `domSegs`/`domSegEntries`, which the @SWAP line prints from cow_chain_stats and dom_cow_chain_stats
       directly — so this census computed them, asserted nothing about them, and no consumer has ever read one.
       A computed writer with no reader is the mirror of the read-with-no-writer defect and is harder to see
       precisely because the number is real: it looks like a measurement right up until someone quotes it. The
       two rows that remain here are the ones the @COLD line reads. */
    long seg_bytes;                                      /* cow.c's frozen heap chain */
    long dom_seg_bytes;                                  /* dom_cow.c's frozen document chain */
    long pin_seg_count, pin_seg_entries, pin_seg_bytes;  /* concolic.c's frozen path constraint */
    long dec_seg_count, dec_seg_entries, dec_seg_bytes;  /* decide.c's frozen decision vector */
} ColdCensus;

/* Walk the frontier and fill `out`. Pure measurement of the components it reads: it takes no reference on
   anything it measures, mutates none of them, and is safe to call between scheduler steps (which is where the
   progress stream calls it).
   IT IS NOT ALLOCATION-FREE, AND THAT IS THE ONE THING A CALLER OWES IT. `program_cursors`' extent is the
   frontier's own rather than a list's, so it cannot be a fixed array on the record and the record therefore
   OWNS a buffer. `cold_census_release` is the other half of that and every census owes it exactly one call. */
void cold_census(ColdCensus *out);

/* Release what a census OWNS, leaving the record readable as one whose walk found nothing. IDEMPOTENT, so a
   composer with several exits does not have to prove it takes exactly one of them — which is the shape the
   caller on the result seam actually has, since a histogram that could not be composed returns early. */
void cold_census_release(ColdCensus *out);

/* ─────────────────────────────────────────────────────────────────────────────────────────────────────────
   THE SECOND CONTRACT — THE RECIPE, which is what actually crosses the tier.
 *
 * WHAT CROSSES IS TEXT AND IT CARRIES ITS TYPE, because a live JSValue crosses neither a process, nor an
 * instance, nor a session, nor a park. The census above says what a snapshot is MADE of; this says which part
 * of it can be WRITTEN DOWN, and the answer is exactly one part. Every other row names its target by a live
 * heap pointer — the COW delta's slots, the DOM head's nodes, the suspended frame chain's bytecode and closed
 * cells, the constraint's segments, the pending register's resolve capabilities — so none of them has an
 * identity outside this session and CLAUDE.md forbids serializing them ("a delta names its target by a live
 * heap pointer with no cross-tier identity"). The DECISION CHAIN is not a pointer at anything: it is the
 * sequence of ARMS the flow took, and flow.h defines a flow as precisely that.
 *
 * SO EVERYTHING ELSE IS REGENERATED BY REPLAYING IT, and that is a claim with a per-row answer:
 *   - the heap + DOM COW delta  — rebuilt by re-running the document's scripts under the recorded arms;
 *   - the suspended frame chain — rebuilt by re-entering the same code, which is why a recipe names no rest
 *                                 point and cannot carry a stale stage index (see decide.h);
 *   - the path constraint       — re-derived at the gates that produced it, which also re-derives the PINS;
 *   - the lazily-loaded chunks  — re-fetched, so a resumed flow reads TODAY's chunk;
 *   - the replies the host owes — re-issued by the replaying code, so they carry today's answers;
 *   - the queued jobs           — re-enqueued by the same reactions, on the same flow's queue, WHICH IS TRUE
 *                                 of every job the replayed program CAUSES and of nothing else. A job handed
 *                                 in from OUTSIDE that program has no cause in the replay to re-cause it, and
 *                                 this engine makes exactly one: the §9.3.3 task a routed cross-document
 *                                 delivery becomes. cold_park_flow refuses that flow and says what closes it.
 * The last three are why §Time-travel-resume says a resumed flow "re-derives example VALUES from CURRENT
 * sources": the path is the snapshot's, the data is today's, and that is the point of the tool rather than a
 * concession. What CANNOT be regenerated is asserted at the park rather than quietly written out wrong.
 *
 * THE SHARING SURVIVES THE TIER. A recipe per flow, written in full, would flatten the prefix every fork
 * shares — the quadratic decide.c deleted from RAM, re-created on the way to disk, and allocated at the one
 * moment RAM pressure asked for relief. So the park writes each frozen SEGMENT once and names it by a
 * park-local ordinal; a flow's own record is that ordinal plus its accumulated reward. Every record is plain
 * text and none may contain the ';' the host joins them with:
 *
 *     g<generation>               THE WORLD-NAME GENERATION this residue was written under, and the FIRST
 *                                 record in the document because everything after it is named under the one
 *                                 above it. A WorldId is (document, generation, serial): the document name is
 *                                 stable across a park BY REQUIREMENT — routing keys on it — and the serial
 *                                 counts from 1 in every session, so without this a resumed session hands a
 *                                 peer that never left memory the names of the session that ended, and the
 *                                 peer answers those flows out of a dead flow's segments (solver/world.h says
 *                                 why the generation and not a park-time notice). A park is the ONLY thing
 *                                 that makes a document name outlive a session, so the residue is the only
 *                                 thing this has to ride, and it rides it as the writer's OWN generation:
 *                                 cold_resume mints one above it rather than trusting a number to be next.
 *     w<vector-hex>               A FOREIGN WORLD'S SEGMENT — a peer document's timeline materialized in this
 *                                 instance, which is the one part of a park that belongs to no flow of this
 *                                 frontier. Written by the WHOLE-frontier park only, because it is a fact
 *                                 about this ENGINE leaving memory and not about a tail of flows going out
 *                                 (solver/world.h says what a segment is and why its vector is the whole of
 *                                 its recipe). The vector is world_serialize's own grammar — colons, commas
 *                                 and whatever the host called a document — so it crosses as HEX for
 *                                 park_hex's reason exactly: an encoding with no charset predicate in it,
 *                                 rather than a fourth writer this grammar has to be kept in step with.
 *                                 EMITTED IN MATERIALIZATION ORDER and rebuilt in it, so an ancestor is
 *                                 already present when the segment forked from it is rebuilt.
 *     s<id>,<base-id|->,<slots>   a frozen segment, over the segment `base-id`. Each SLOT is NINE characters:
 *                                 the arm as '0'/'1', then the eight lower-case hex digits of the QUESTION it
 *                                 answers — decide.c's 32-bit FNV-1a of the constraint key. The question
 *                                 crosses the tier because a resumed flow replays at cursor 0 against today's
 *                                 code and today's replies, so it can ask a different SEQUENCE than the run
 *                                 that recorded these arms; until the key was here it consumed them anyway,
 *                                 positionally, taking another predicate's arm at every branch from the
 *                                 divergence onward and emitting output identical to a clean resume's. There
 *                                 is no version field and none is wanted: nothing else this grammar writes is
 *                                 nine characters wide, so a segment field that does not divide by nine is
 *                                 residue from a writer that recorded arms with no questions, and cold_resume
 *                                 refuses it BY NAME rather than reading it as a shorter chain of arms that
 *                                 would all be plausible and all be unverifiable.
 *     f<seg-id|->,<val>           a flow standing on that segment, carrying its WFQ reward
 *     c<seg-id|->,<val>,<sink>,<src-hex>,<root-hex>,<payload-hex>
 *                                 an @S CANDIDATE SESSION: an 'f' record PLUS the substitution that makes it a
 *                                 candidate rather than an exploration flow. A candidate is an ordinary member
 *                                 of the one frontier, so it branches and is preempted like anything else and
 *                                 needs its path; and its IDENTITY is what it injects, so it needs that too.
 *                                 `sink` is solve.c's sink-class NAME, re-bound to that table's own pointer by
 *                                 solve_resume_candidate (a `cand_sink` is a pointer into static storage and
 *                                 has no identity outside the session that minted it). The source, the root
 *                                 and the payload cross as lower-case HEX — the payload is ATTACKER TEXT and
 *                                 never an index into solve.c's breakout tables, which §@S's derived-breakout
 *                                 work will delete, and an index into a table that no longer exists is still a
 *                                 valid index. `cand_verifying` and `cand_fired` deliberately do NOT cross;
 *                                 see cold.c's park_rec_cand for why dropping the second is what keeps a
 *                                 recorded PoC an observation rather than an inherited claim.
 *                                 `root` IS THE DELIVERY PROVENANCE AND NOT A SECOND SPELLING OF `src`. The
 *                                 source is the injection IDENTITY a payload is substituted at — a DERIVED one
 *                                 (`{location.hash}.slice()`) included, because that is where the substitution
 *                                 has to land — while the root is the declared browser source those bytes came
 *                                 in through, which is what §S(d)'s reproduction envelope is built from. It is
 *                                 asked of solve.c at both ends rather than read off the Flow, because it is a
 *                                 fact about the sink SEARCH: one sink's N candidates share one root, and
 *                                 solve.c's cand_learn_root asserts every record of them agrees. Without this
 *                                 field the resuming session had NO other way to learn it — a verifying flow
 *                                 does not detect — so every emit of the search aborted on solve.c's own
 *                                 assert, and a release build rendered "nothing carries these bytes" over a
 *                                 payload whose delivery the ended session knew exactly.
 *     o<locator-hex>              WHICH FUNCTION A DRIVEN ORPHAN IS DRIVING — sixteen lower-case hex digits,
 *                                 quickjs's JS_OrphanHash of the script the body was compiled from, the
 *                                 position in that script, and the body's own source text. It belongs to the
 *                                 flow record IMMEDIATELY BEFORE IT, the same positional binding an unmade
 *                                 delivery uses, and it is a FIELD rather than a KIND on purpose: being a
 *                                 driven orphan is not an alternative to being a flow or a candidate but a
 *                                 fact about one, and an orphan drive forked inside an @S candidate session is
 *                                 both at once. So an ordinary drive is 'f' then 'o' and a candidate's drive
 *                                 is 'c' then 'o', where a third KIND would have had to discard one of two
 *                                 identities the engine legitimately holds together.
 *                                 IT IS THE ONE THING A DECISION VECTOR CANNOT REPRODUCE. Every other flow's
 *                                 recipe is (path, reward) and a resume RE-RUNS THE DOCUMENT under it, which
 *                                 reproduces the flow — and re-running the document is exactly the run that
 *                                 never calls an uncalled function. The resumed flow therefore replays like
 *                                 any other (which is what re-creates the closure and consumes the recorded
 *                                 arms) and, at the point its work runs out — the point the drive stood at in
 *                                 the session that recorded it — is handed the body this locator names and
 *                                 builds its own call. Fixed width and separator-free for a decision slot's
 *                                 reason: the field is the whole record, so a different width is another
 *                                 writer's document and is refused rather than read as a shorter name. A hash
 *                                 of the SOURCE TEXT ALONE is the one composition that does not work — a
 *                                 minified bundle repeats one-line bodies dozens of times, so the name would
 *                                 identify a SET and the resume would drive whichever member the heap walk met
 *                                 first.
 *     r<vector-hex>,<0|1>         WHICH SENDING TIMELINE A RECEIVING ONE IS IN — the world a cross-document
 *                                 message came from, and whether this timeline RECEIVED it (1) or FORECLOSED
 *                                 it (0) as the arm of a delivery-time fork. Bound by POSITION to the flow
 *                                 record before it and a FIELD rather than a kind, for the orphan locator's
 *                                 reason: being in a sender's arm is a fact ABOUT a flow and not an
 *                                 alternative to being one, and a candidate session receives messages like
 *                                 any other member.
 *                                 IT IS NOT DERIVABLE FROM THE 'm' RECORDS BESIDE IT. Those are the messages
 *                                 this timeline still owes; a commitment is one it already made, and the
 *                                 queue forgot it at the delivery. A flow rebuilt without them comes back as
 *                                 a receiver committed to nothing, so the first pair of CONTRADICTORY sender
 *                                 arms it is handed is delivered in sequence — a timeline neither sender was
 *                                 ever in, which is exactly what the fork at the delivery exists to prevent.
 *                                 The vector crosses as HEX for park_hex's reason (it holds the colons and
 *                                 commas world_serialize writes, and whatever the host called the root
 *                                 document); the flag is written rather than inferred because the two kinds
 *                                 refuse different things, so a dropped one would be read as whichever kind
 *                                 the first test asked for.
 *
 * Ordinals are dense and ascending in EMISSION order, and a base is always emitted before anything that names
 * it, so the rebuild is one forward pass with nothing to patch up.
 *
 * A RECIPE IS HALF OF THE STORED ENTRY, AND THE OTHER HALF IS THE HOST'S. These arms replay INSIDE a document,
 * so a resume needs the document they replay in — its bytes, its address, its top-level creation URL, its
 * browser-stated principal and its RESPONSE HEADER LIST, which is HTML §7.1.7 "Policy containers" and is what
 * qjs_init takes beside the arms qjs_begin takes. None of those is derivable from the others, none of them may
 * be defaulted, and the host that stores the recipe stores them with it (extension/bridge.js's frontier entry;
 * the fixture's second spawn re-states them). A stored entry short of one is a document that resumes into an
 * environment its flows never ran in — the header list was the one that was missing. */

/* WRITE ONE FLOW'S RECIPE INTO THE PARK DOCUMENT — the primitive, and the unit a PARTIAL self-park is made of
   (§scheduler: "an engine self-parks its residue to the IDB cold tier under pressure"). The flow must be one
   the scheduler is not switched into, for the same reason flow_release demands it: its decision state is live
   in decide.c until a suspend freezes it, so its recipe would be short every arm it has taken since. It marks
   the flow `paged`, which is what lets flow_release let go of a parked continuation, and refuses to write the
   same flow twice — the host stores ONE value per bundle, so a flow named twice comes back as two flows on one
   path. Writing it does NOT remove it: the caller decides whether this flow's RAM comes back now
   (flow_release) or with the instance. */
void cold_park_flow(Flow *f);

/* WRITE THE WHOLE FRONTIER OUT — the loop over the primitive above, and nothing else. That is the Level-1
   eviction §scheduler describes: the host ranks DOCUMENTS' engines, asks the lowest-value one to give up its
   residue, and the RAM comes back when that instance is torn down. Called with no flow switched in, which the
   primitive asserts per flow. It is deliberately not the TAIL SELECTION a lone over-budget engine needs — which
   flows go and how far down the frontier to go — see the OOM CHECK in engine.c's flow-compile path.
   A FRONTIER WITH NO MEMBERS WRITES NO BYTES AT ALL, which is the positive answer cold_park_recipes describes
   and not a refusal. The host decides WHEN it wants the residue and the engine decides what the residue IS, so
   a park asked for over an empty registry is ANSWERED rather than rejected — and an engine reaches that state
   honestly: a peer holding a reference into this document keeps the session live past its own last flow, and
   an engine that met the RAM floor may have sold every flow it had through the primitive above. What a park
   may NOT do is write a PREAMBLE with no flow under it — the generation, a peer's segment — because that is a
   non-empty recipe string the host stores like any residue, and the next session then takes it over its boot
   flow and opens on an empty frontier, which is a document nothing will ever explore again. Both ends assert
   it: this writer refuses to leave a document naming no flow, and cold_resume refuses to read one. */
void cold_park(void);

/* THE PARK DOCUMENT AS THIS FILE HOLDS IT — the ';'-joined records, which is exactly the string cold_resume
   parses. "" until a flow is written, and that emptiness is the POSITIVE answer engine_sched_begin reads as
   "no residue, seed a boot flow" (a document that drained deletes its cold entry rather than storing one).
   IT IS THE CANONICAL FORM AND THE JSON BELOW IS A TRANSPORT, which is a correction and not a preference: the
   buffer used to hold JSON while the reader parsed ';'-joined text, so the only producer of the reader's own
   language anywhere in the system was `extension/bridge.js` joining the array it had stored. No process held
   both ends, and the entire read half — the 's'/'c' rebuilds, park_unhex, solve_resume_candidate — was
   therefore unreachable from any host without an IndexedDB. A host that can store a string (the fixture stores
   a file) stores this and hands it back to engine_sched_begin unchanged. Borrowed; freed by cold_free. */
const char *cold_park_recipes(void);

/* HOW MANY RECORDS ARE IN IT — the writer's own count, not a second parse of its output. A host that wants to
   say what it stored asks; a host that counted the ';' itself would be a second speller of the grammar. */
long cold_park_records(void);

/* …AND WHICH KINDS THEY ARE, which is the only thing that can say how DEEP a park was. The two ends of the
   tier are asked the same question in the same shape (ColdResumed below) because they are one round trip: a
   residue of nothing but `f-,<val>` records — every flow standing on no decision segment, which is what a park
   taken before the first pick writes — resumes without touching park_emit_chain's output, park_unhex or the
   sink-class re-bind, and reports the identical record count as one taken after the document forked. A host
   that cannot tell those apart cannot tell an exercised round trip from an unexercised one.
   THE 'g' RECORD IS NOT A KIND HERE, and that is deliberate rather than an omission: there is exactly one per
   document and it names no flow, so counting it would put a constant in every one of these numbers. It is in
   cold_park_records (which is what the document HOLDS) and in neither census (which are what it RESUMES). */
typedef struct {
    long segs;     /* 's': frozen decision segments, written once each however many flows stand on them */
    long flows;    /* 'f' */
    long cands;    /* 'c' */
    /* 'w': FOREIGN world segments — the peers' timelines this instance is carrying across the tier. It is a
       kind here and not a constant like 'g' because there are as many as this instance answered peers, and
       zero is a real and different answer: an instance that never answered anything. */
    long worlds;
    /* 'o': the function locators — one per flow that is a DRIVEN ORPHAN. Not a kind and so not part of
       flows+cands: it is a field of the record before it, which is why it is counted separately rather than
       added to either. Zero is a real answer and a loud one on a large bundle — it means this park is carrying
       no forced invocation at all, so the next session inherits the document's explored paths and none of its
       uncalled code. */
    long orphans;
} ColdParked;
void cold_parked(ColdParked *out);

/* WHAT A PARK TAKEN NOW WOULD WRITE — the same question ColdParked answers about a park that has happened,
 * asked BEFORE one is taken, because that is the question a Level-1 eviction actually is. §scheduler puts the
 * decision in the HOST ("the host orders live per-page engines by best-flow weight… an engine self-parks its
 * residue to the IDB cold tier under pressure"), so the host has to see the residue in the RECIPE's own terms.
 *
 * A HOST THAT INSTEAD ASKS ONE OF THE ENGINE'S REGISTERS IS ASKING ABOUT SOMETHING ELSE, AND ONE DID — which is
 * the whole reason this exists rather than each host writing its own walk. test_forced.c's park hook was
 *     solve_candidate_count() > 0 && engine_host_owes()
 * and the seam is consulted at exactly one point: the top of run_scheduler's loop, immediately after the
 * provider has been paid, where that same loop's two asserts state that BOTH host registers are empty. So the
 * second conjunct was FALSE BY CONSTRUCTION wherever the question is asked, the park was never once taken, and
 * the entire read half of this file — park_unhex, solve_resume_candidate, the 's'/'c' rebuilds — had still
 * never executed in any process. A predicate whose answer is fixed reads exactly like one that is merely not
 * true yet, and nothing in the run says which: the @COLDPARK census reports zeroes either way.
 *
 * IT SHARES THE RECORD-KIND SELECTION WITH cold_park_flow, so the two cannot answer differently, and cold_park
 * asserts the pair against each other at every park. `deep` is the flows whose record will NAME A SEGMENT —
 * exactly the ones that make a park write 's' records at all — and it answers for the RUNNING flow too, whose
 * decision state is live in decide.c rather than in its blob (the same split cold_census makes, and the reason
 * this cannot be a hand-written loop over `f->dec_blob` in a host: at the moment the host is asked, one flow's
 * blob is NULL because it holds the thread, not because it stands on nothing). Pure measurement: it takes no
 * reference, mutates nothing, and assigns no ordinal. */
typedef struct {
    long flows, cands;           /* the records a park taken now would write, per kind */
    long deep;                   /* …of those, the ones standing on a frozen decision segment */
    /* …AND THE INTERSECTION, which is a DIFFERENT MOMENT and not a refinement of either count. A host that wants
       the residue to exercise every arm of the recipe grammar at once needs a CANDIDATE that stands on a segment:
       that is the one member whose record carries attacker text (park_hex) AND names a segment ordinal, so a
       residue holding one crosses both. `cands && deep` cannot say it — an exploring arm that forked satisfies
       `deep` while every candidate is still unstarted — and it stopped being able to the moment candidates began
       being seeded during exploration rather than after it (engine.c's pick). Two counts whose conjunction was
       read as an intersection is the same defect as a field defaulted by its consumer. */
    long deepcands;
    /* AND THE PART OF THE RESIDUE THAT IS NOT A WALK OF THE FRONTIER AT ALL — the foreign world segments this
       instance holds. It is here because the preview's contract is "the residue the host is about to be
       shown", and a host that evicted on a description missing them would be storing a document larger than
       the one it was told about. It is also the only row a whole-frontier park writes and a partial one does
       not, which is what makes cold_park's two-sided check able to say so.
       ZERO WHERE THERE IS NO DOCUMENT TO CARRY THEM IN, because a park that names no flow writes no bytes at
       all (see cold_park). The two answers come from one predicate rather than from a rule restated at each
       end — a preview promising a segment the park then leaves out is exactly the disagreement the two-sided
       check exists to catch, and it would be a disagreement this file wrote into itself. */
    long worlds;
    /* AND THE DRIVES AMONG THE MEMBERS — the 'o' records a park taken now would write. It is here for the
       preview's whole contract: the host decides to evict on the strength of this description, so a row the
       description leaves out is a record the residue turns out to hold. */
    long orphans;
} ColdPreview;
void cold_park_preview(ColdPreview *out);

/* …AND THE SAME DOCUMENT AS THE JSON ARRAY the result document carries, rendered from the records on demand —
   "[]" when there are none. IndexedDB is what the trusted zone has, so the array is what crosses to it; the
   render is where "no record needs JSON escaping" is asserted, once, instead of being trusted separately by
   each of the four record writers. Borrowed; freed by cold_free. */
const char *cold_park_json(void);

/* MERGE a parked residue INTO the frontier: the ';'-joined records the host stored, back into flows on the ONE
   frontier, re-ranked by the same weight as everything else. Each becomes a flow that RESUMES (it stands on a
   recorded chain) with no frame and cursor 0, so it replays its arms as it re-runs the document from its first
   script and forks normally the moment its recipe runs out.
   IT APPENDS — it does not seed. The frontier it lands in may already have members (a partial park's tail comes
   back to the flows that were not paged out), so the document's park-local ordinals are resolved against a
   table local to THIS call and no live member is read, renumbered or displaced; both directions are asserted at
   the merge. Whether a SESSION starts from a residue or from a fresh boot flow is engine_sched_begin's choice,
   not this call's — they are alternatives, and the frontier is seeded once. */
void cold_resume(JSContext *ctx, const char *recipes);

/* WHAT THE LAST cold_resume REBUILT, PER RECORD KIND — the observable that says which ARMS of the grammar ran.
   `@RESUMED <n>` is printed for the extension because a line on stdout is the only channel that zone has, and
   a single total cannot distinguish a residue of nothing but plain flows from one that also carried an @S
   candidate (park_unhex, solve_resume_candidate). A host that can call C asks here.
   THERE WAS A FOURTH KIND AND ITS LETTER IS RETIRED, not reused: 'd' named an engine-seeded DISCOVERY PROBE,
   one flow per candidate document address, and active discovery is the trusted zone's again
   (extension/lib/discovery-probe.js). Both ends of the round trip lost it in the same change — a grammar that
   can still EMIT a kind it can no longer PARSE fails only on a resume in a later session, which is the one
   failure this document exists to make impossible. cold_resume names 'd' in its refusal so a residue written
   by an older session says what wrote it. */
typedef struct {
    long segs;     /* frozen decision segments rebuilt from 's' records — the shared prefixes every flow stands on */
    long flows;    /* 'f': exploration flows */
    long cands;    /* 'c': @S candidate sessions, each carrying a hex source and payload */
    long worlds;   /* 'w': foreign world segments re-materialized from the vectors that first built them */
    /* 'o': the drives this rebuild inherited — flows waiting to be handed back the function they were driving.
       It is a SUBSET of `flows`+`cands` and never a summand of them, because an 'o' record names the flow
       before it rather than producing one. It is also the first half of the round trip's only observable: the
       engine reports it against how many of those waits a take SATISFIED and how many waiting flows FINISHED
       never having been handed a body (`orphanClaims`/`orphanClaimsMet`/`orphanClaimsUnmet`). The last is the
       verdict — ZERO on a document whose bytes did not change between two sessions — and the middle one may
       legitimately exceed this count, because a waiting drive forks arms while it replays and every arm of it
       is the same drive of the same body. */
    long orphans;
} ColdResumed;
void cold_resumed(ColdResumed *out);

void cold_free(void);

#endif
