/* THE COLD TIER — RAM holds the hot working set; the lowest-value SUSPENDED flows page out and resume on
 * demand, byte-identically. See CLAUDE.md §Time-travel-resume ("the cold low-value tail serializes to IDB as
 * suspended snapshots and resumes on demand"), §scheduler ("STARVE means deprioritize-and-page, NEVER
 * terminate"; "an engine self-parks its residue to the IDB cold tier under pressure") and engine.c's own
 * flow-compile OOM, which names this file as what carries past the RAM floor.
 *
 * ITS FIRST CONTRACT IS THE CENSUS, and that ordering was not a preamble to the work — it decided the work.
 * A pager cannot be written for a snapshot nobody can describe: what crosses the boundary decides the encoder,
 * and what is SHARED between siblings decides whether writing one flow's snapshot writes its siblings' too.
 * Both questions were answered by the numbers below and both answers are now load-bearing in the RECIPE (the
 * second contract, further down): the shared chains are what the park writes ONCE and names by ordinal, and
 * the per-flow rows are what a replay regenerates instead of writing at all. The two chains that already report themselves (cow.c's `heapSegs`, dom_cow.c's `domSegs`) say
 * the sharing works — they were flat at 14/727 and 18/5160 across 14003 flows — and everything else in a
 * snapshot had no number at all. This is that number, per part, so a part that turns out to be a per-flow COPY
 * of state its parent already holds is visible as one instead of being paged out N times.
 *
 * WHAT A SNAPSHOT IS, in the order §Time-travel-resume names it: the flow's per-flow COW delta (its heap AND
 * DOM writes) plus its suspended heap-frame chain, plus the rest of what the scheduler swaps with it — the
 * decision vector and its cursor, the path constraint, the queued jobs, the replies the host still owes, and
 * the flow's own byte state (its lazily-loaded chunk bodies, its candidate substitution, a routed record).
 * Each of those is a row here, and each row is either PER-FLOW or SHARED; the pair is the whole design
 * question, so the census answers it directly rather than reporting one total. */
#ifndef ENGINE_HOST_SOLVER_COLD_H
#define ENGINE_HOST_SOLVER_COLD_H

#include "quickjs.h"
#include "solver/flow.h"   /* the park's unit is ONE member of the frontier */

/* WHAT THE FRONTIER'S SNAPSHOTS ARE MADE OF. Every `*_bytes` is host `malloc` unless the row says otherwise:
   the runtime's own allocations (the frame chains, the step machines) are counted by quickjs and reported in
   the @HEAP line's `unattributed` residual, which is named here rather than restated. */
typedef struct {
    long flows;              /* live members of the frontier */
    /* … suspended inside a live heap-frame chain. This said "the part with no encoder yet", which was the
       right thing to record before there was a recipe and is the wrong thing to leave standing now: the frame
       chain is not encoded and is not OWED an encoder — it is REGENERATED by replaying the flow's arms, which
       is what makes a recipe immune to the stale-stage-index failure a serialized rest point would have. What
       the number is FOR is the park's cost: a framed flow is one whose resume has to re-execute the document
       to get back where it was, so this is how much of the frontier pays that. */
    long framed;
    long blocked;            /* … holding an unanswered host request */

    /* PER-FLOW rows — these multiply by the number of parked flows, so they are what a pager pays for. */
    long dec_entries;        /* decision-vector slots the flows STAND ON — a chain total, so this counts the
                                same shared prefix once per flow that references it and is deliberately NOT a
                                byte figure. It is the number that was quadratic when the vector was copied. */
    long dec_bytes;          /* …and what the flows themselves own for it: one blob header each. There is no
                                second row for a BIRTH vector any more: the flat per-flow array a from-baseline
                                flow used to be able to carry is deleted, and a flow that stands on a recorded
                                path — forked or resumed from the cold tier — stands on the shared chain. */
    long head_entries;       /* heap COW delta HEADS (the writes each flow has made since its last fork) */
    long head_bytes;
    long dom_head_entries;   /* the DOM half of the same */
    long dom_head_bytes;
    long job_count;          /* queued microtasks/tasks */
    long pend_count;         /* replies the host still owes */
    long pend_bytes;
    long dyn_bytes;          /* this flow's own lazily-loaded chunk bodies */
    long misc_bytes;         /* the Flow struct, its candidate substitution, a routed record, the blob headers */

    /* SHARED rows — counted ONCE for the whole frontier, because a frozen segment is referenced by every flow
       that forked below it. A pager that wrote these per flow would multiply the sharing back out. */
    long seg_count, seg_entries, seg_bytes;              /* cow.c's frozen heap chain */
    long dom_seg_count, dom_seg_entries, dom_seg_bytes;  /* dom_cow.c's frozen document chain */
    long pin_seg_count, pin_seg_entries, pin_seg_bytes;  /* concolic.c's frozen path constraint */
    long dec_seg_count, dec_seg_entries, dec_seg_bytes;  /* decide.c's frozen decision vector */
} ColdCensus;

/* Walk the frontier and fill `out`. Pure measurement: it takes no reference, mutates nothing, and is safe to
   call between scheduler steps (which is where the progress stream calls it). */
void cold_census(ColdCensus *out);

/* ─────────────────────────────────────────────────────────────────────────────────────────────────────────
   THE SECOND CONTRACT — THE RECIPE, which is what actually crosses the tier.
 *
 * WHAT CROSSES IS TEXT AND IT CARRIES ITS TYPE, because a live JSValue crosses neither a process, nor an
 * instance, nor a session, nor a park. The census above says what a snapshot is MADE of; this says which part
 * of it can be WRITTEN DOWN, and the answer is exactly one part. Every other row names its target by a live
 * heap pointer — the COW delta's slots, the DOM head's nodes, the suspended frame chain's bytecode and closed
 * cells, the constraint's segments, the pending register's resolve capabilities — so none of them has an
 * identity outside this session and CLAUDE.md forbids serializing them ("a delta names its target by a live
 * heap pointer with no cross-tier identity"). The DECISION CHAIN is not a pointer at anything: it is the
 * sequence of ARMS the flow took, and flow.h defines a flow as precisely that.
 *
 * SO EVERYTHING ELSE IS REGENERATED BY REPLAYING IT, and that is a claim with a per-row answer:
 *   - the heap + DOM COW delta  — rebuilt by re-running the document's scripts under the recorded arms;
 *   - the suspended frame chain — rebuilt by re-entering the same code, which is why a recipe names no rest
 *                                 point and cannot carry a stale stage index (see decide.h);
 *   - the path constraint       — re-derived at the gates that produced it, which also re-derives the PINS;
 *   - the lazily-loaded chunks  — re-fetched, so a resumed flow reads TODAY's chunk;
 *   - the replies the host owes — re-issued by the replaying code, so they carry today's answers;
 *   - the queued jobs           — re-enqueued by the same reactions, on the same flow's queue.
 * The last three are why §Time-travel-resume says a resumed flow "re-derives example VALUES from CURRENT
 * sources": the path is the snapshot's, the data is today's, and that is the point of the tool rather than a
 * concession. What CANNOT be regenerated is asserted at the park rather than quietly written out wrong.
 *
 * THE SHARING SURVIVES THE TIER. A recipe per flow, written in full, would flatten the prefix every fork
 * shares — the quadratic decide.c deleted from RAM, re-created on the way to disk, and allocated at the one
 * moment RAM pressure asked for relief. So the park writes each frozen SEGMENT once and names it by a
 * park-local ordinal; a flow's own record is that ordinal plus its accumulated reward. Two record kinds, both
 * plain text, and neither may contain the ';' the host joins them with:
 *
 *     s<id>,<base-id|->,<arms>    a frozen segment: its own arms as '0'/'1', over the segment `base-id`
 *     f<seg-id|->,<val>           a flow standing on that segment, carrying its WFQ reward
 *     d<val>,<url>                a DISCOVERY PROBE (solver/discovery.h) — the one flow whose identity is not a
 *                                 path through the page but an ADDRESS it has still to read, so the address is
 *                                 what crosses and the resumed flow re-issues the GET. It is the last field and
 *                                 runs to the end of the record, which is what lets a query carry a ','.
 *     c<seg-id|->,<val>,<sink>,<src-hex>,<payload-hex>
 *                                 an @S CANDIDATE SESSION: an 'f' record PLUS the substitution that makes it a
 *                                 candidate rather than an exploration flow. A candidate is an ordinary member
 *                                 of the one frontier, so it branches and is preempted like anything else and
 *                                 needs its path; and its IDENTITY is what it injects, so it needs that too.
 *                                 `sink` is solve.c's sink-class NAME, re-bound to that table's own pointer by
 *                                 solve_resume_candidate (a `cand_sink` is a pointer into static storage and
 *                                 has no identity outside the session that minted it). The source and the
 *                                 payload are ATTACKER TEXT and cross as lower-case HEX — never as an index
 *                                 into solve.c's breakout tables, which §@S's derived-breakout work will
 *                                 delete, and an index into a table that no longer exists is still a valid
 *                                 index. `cand_verifying` and `cand_fired` deliberately do NOT cross; see
 *                                 cold.c's park_rec_cand for why dropping the second is what keeps a recorded
 *                                 PoC an observation rather than an inherited claim.
 *
 * Ordinals are dense and ascending in EMISSION order, and a base is always emitted before anything that names
 * it, so the rebuild is one forward pass with nothing to patch up. */

/* WRITE ONE FLOW'S RECIPE INTO THE PARK DOCUMENT — the primitive, and the unit a PARTIAL self-park is made of
   (§scheduler: "an engine self-parks its residue to the IDB cold tier under pressure"). The flow must be one
   the scheduler is not switched into, for the same reason flow_release demands it: its decision state is live
   in decide.c until a suspend freezes it, so its recipe would be short every arm it has taken since. It marks
   the flow `paged`, which is what lets flow_release let go of a parked continuation, and refuses to write the
   same flow twice — the host stores ONE value per bundle, so a flow named twice comes back as two flows on one
   path. Writing it does NOT remove it: the caller decides whether this flow's RAM comes back now
   (flow_release) or with the instance. */
void cold_park_flow(Flow *f);

/* WRITE THE WHOLE FRONTIER OUT — the loop over the primitive above, and nothing else. That is the Level-1
   eviction §scheduler describes: the host ranks DOCUMENTS' engines, asks the lowest-value one to give up its
   residue, and the RAM comes back when that instance is torn down. Called with no flow switched in, which the
   primitive asserts per flow. It is deliberately not the TAIL SELECTION a lone over-budget engine needs — which
   flows go and how far down the frontier to go — see the OOM CHECK in engine.c's flow-compile path. */
void cold_park(void);

/* THE PARK DOCUMENT AS THIS FILE HOLDS IT — the ';'-joined records, which is exactly the string cold_resume
   parses. "" until a flow is written, and that emptiness is the POSITIVE answer engine_sched_begin reads as
   "no residue, seed a boot flow" (a document that drained deletes its cold entry rather than storing one).
   IT IS THE CANONICAL FORM AND THE JSON BELOW IS A TRANSPORT, which is a correction and not a preference: the
   buffer used to hold JSON while the reader parsed ';'-joined text, so the only producer of the reader's own
   language anywhere in the system was `extension/bridge.js` joining the array it had stored. No process held
   both ends, and the entire read half — the 's'/'c'/'d' rebuilds, park_unhex, solve_resume_candidate — was
   therefore unreachable from any host without an IndexedDB. A host that can store a string (the fixture stores
   a file) stores this and hands it back to engine_sched_begin unchanged. Borrowed; freed by cold_free. */
const char *cold_park_recipes(void);

/* HOW MANY RECORDS ARE IN IT — the writer's own count, not a second parse of its output. A host that wants to
   say what it stored asks; a host that counted the ';' itself would be a second speller of the grammar. */
long cold_park_records(void);

/* …AND WHICH KINDS THEY ARE, which is the only thing that can say how DEEP a park was. The two ends of the
   tier are asked the same question in the same shape (ColdResumed below) because they are one round trip: a
   residue of nothing but `f-,<val>` records — every flow standing on no decision segment, which is what a park
   taken before the first pick writes — resumes without touching park_emit_chain's output, park_unhex or the
   sink-class re-bind, and reports the identical record count as one taken after the document forked. A host
   that cannot tell those apart cannot tell an exercised round trip from an unexercised one. */
typedef struct {
    long segs;     /* 's': frozen decision segments, written once each however many flows stand on them */
    long flows;    /* 'f' */
    long cands;    /* 'c' */
    long probes;   /* 'd' */
} ColdParked;
void cold_parked(ColdParked *out);

/* WHAT A PARK TAKEN NOW WOULD WRITE — the same question ColdParked answers about a park that has happened,
 * asked BEFORE one is taken, because that is the question a Level-1 eviction actually is. §scheduler puts the
 * decision in the HOST ("the host orders live per-page engines by best-flow weight… an engine self-parks its
 * residue to the IDB cold tier under pressure"), so the host has to see the residue in the RECIPE's own terms.
 *
 * A HOST THAT INSTEAD ASKS ONE OF THE ENGINE'S REGISTERS IS ASKING ABOUT SOMETHING ELSE, AND ONE DID — which is
 * the whole reason this exists rather than each host writing its own walk. test_forced.c's park hook was
 *     solve_candidate_count() > 0 && engine_host_owes()
 * and the seam is consulted at exactly one point: the top of run_scheduler's loop, immediately after the
 * provider has been paid, where that same loop's two asserts state that BOTH host registers are empty. So the
 * second conjunct was FALSE BY CONSTRUCTION wherever the question is asked, the park was never once taken, and
 * the entire read half of this file — park_unhex, solve_resume_candidate, the 's'/'c'/'d' rebuilds — had still
 * never executed in any process. A predicate whose answer is fixed reads exactly like one that is merely not
 * true yet, and nothing in the run says which: the @COLDPARK census reports zeroes either way.
 *
 * IT SHARES THE RECORD-KIND SELECTION WITH cold_park_flow, so the two cannot answer differently, and cold_park
 * asserts the pair against each other at every park. `deep` is the flows whose record will NAME A SEGMENT —
 * exactly the ones that make a park write 's' records at all — and it answers for the RUNNING flow too, whose
 * decision state is live in decide.c rather than in its blob (the same split cold_census makes, and the reason
 * this cannot be a hand-written loop over `f->dec_blob` in a host: at the moment the host is asked, one flow's
 * blob is NULL because it holds the thread, not because it stands on nothing). Pure measurement: it takes no
 * reference, mutates nothing, and assigns no ordinal. */
typedef struct {
    long flows, cands, probes;   /* the records a park taken now would write, per kind */
    long deep;                   /* …of those, the ones standing on a frozen decision segment */
} ColdPreview;
void cold_park_preview(ColdPreview *out);

/* …AND THE SAME DOCUMENT AS THE JSON ARRAY the result document carries, rendered from the records on demand —
   "[]" when there are none. IndexedDB is what the trusted zone has, so the array is what crosses to it; the
   render is where "no record needs JSON escaping" is asserted, once, instead of being trusted separately by
   each of the four record writers. Borrowed; freed by cold_free. */
const char *cold_park_json(void);

/* MERGE a parked residue INTO the frontier: the ';'-joined records the host stored, back into flows on the ONE
   frontier, re-ranked by the same weight as everything else. Each becomes a flow that RESUMES (it stands on a
   recorded chain) with no frame and cursor 0, so it replays its arms as it re-runs the document from its first
   script and forks normally the moment its recipe runs out.
   IT APPENDS — it does not seed. The frontier it lands in may already have members (a partial park's tail comes
   back to the flows that were not paged out), so the document's park-local ordinals are resolved against a
   table local to THIS call and no live member is read, renumbered or displaced; both directions are asserted at
   the merge. Whether a SESSION starts from a residue or from a fresh boot flow is engine_sched_begin's choice,
   not this call's — they are alternatives, and the frontier is seeded once. */
void cold_resume(JSContext *ctx, const char *recipes);

/* WHAT THE LAST cold_resume REBUILT, PER RECORD KIND — the observable that says which ARMS of the grammar ran.
   `@RESUMED <n>` is printed for the extension because a line on stdout is the only channel that zone has, and
   a single total cannot distinguish a residue of nothing but plain flows from one that also carried an @S
   candidate (park_unhex, solve_resume_candidate) or a discovery probe. A host that can call C asks here. */
typedef struct {
    long segs;     /* frozen decision segments rebuilt from 's' records — the shared prefixes every flow stands on */
    long flows;    /* 'f': exploration flows */
    long cands;    /* 'c': @S candidate sessions, each carrying a hex source and payload */
    long probes;   /* 'd': discovery probes, each an address to re-issue */
} ColdResumed;
void cold_resumed(ColdResumed *out);

void cold_free(void);

#endif
