/* GENERATED by engine/i18nglobalgen.mjs from https://tc39.es/ecma402/ — DO NOT EDIT.
 * Every global property name ECMA-402 §8 The Intl Object defines. It is derived as the RECEIVER that
 * clause's member subclauses share — they spell themselves `Intl.Collator ( . . . )` and the text before
 * the dot is the object they are members OF — never by widening an IdentifierName test to admit the dot,
 * which would enter `Intl.Collator` in a table of GLOBAL names. solver/absent.c reads this beside
 * browser/platform_names.h and browser/language_names.h: the three vocabularies that own names on the global
 * object, which is what lets it tell a component this engine OWES from server-injected app state.
 * Derived from: https://tc39.es/ecma402/
 * Corpus edition: Draft ECMA-402 / September 15, 2026
 * Members voting for this receiver: 12 */
#ifndef APICLIENT_I18N_NAMES_H
#define APICLIENT_I18N_NAMES_H

static const char *const I18N_NAMES[] = {
    "Intl",
};

#endif
