/* GENERATED by engine/idlgen.mjs from @webref/idl — DO NOT EDIT.
 * Web IDL §3.3.14 [Unscopable] as §3.7.3 Interface prototype object performs it: for each interface that
 * declares any [Unscopable] member, the identifiers §3.7.3's loop puts in that prototype's
 * %Symbol.unscopables% object, and the §3.3.7 [Exposed] set each one is filtered by.
 *
 * A ROW'S EXISTENCE IS §3.7.3's OUTER CONDITION and a member's `set` is its INNER LOOP — "If interface has
 * any member DECLARED with the [Unscopable] extended attribute" against "For each EXPOSED member member of
 * interface that is declared with the [Unscopable] extended attribute". An interface every one of whose
 * [Unscopable] members this realm does not expose still carries an EMPTY unscopables object, because the
 * outer condition asks what the interface declares; an interface with no row carries no property at all.
 * The two are observably different — `Symbol.unscopables in Foo.prototype` — so they are two questions.
 *
 * A MIXIN HAS NO ROW. §3.7.3 mints an interface prototype object "for every interface defined", which an
 * interface mixin is not, and §2.3 "Interface mixins" makes its members the INCLUDING interface's — an
 * includes statement is "used to declare that all objects implementing an interface I (identified by the
 * first identifier) must additionally include the members of interface mixin M (identified by the second
 * identifier)". So a mixin's [Unscopable] member appears on every interface that includes it, and on no
 * row of its own.
 *
 * NO ROW MEANS NO PROPERTY, and that is the sound direction here rather than the usual one: everywhere
 * else in this engine's generated tables a missing row must not REMOVE something, and here a row is what
 * ADDS a property, so a name the corpus does not declare [Unscopable] keeps the ordinary `with` scoping it
 * has today. Regenerate after `npm install @webref/idl webidl2`, and commit the result — the build has no
 * network and this table is not optional. */
#ifndef APICLIENT_IDL_UNSCOPABLES_H
#define APICLIENT_IDL_UNSCOPABLES_H

/* One member's contribution to §3.7.3's `CreateDataPropertyOrThrow(unscopableObject, id, true)`. The value
   is not stored: §3.7.3 writes `true` for every one of them. */
typedef struct IdlUnscopableMember {
    const char *id;    /* §3.7.3's "Let id be member's identifier" */
    unsigned    set;   /* §3.3.7's exposure set as §3.3.8 global-name bits; IDL_EXPOSED_STAR for `*` */
} IdlUnscopableMember;

typedef struct IdlUnscopablesRow {
    const char                 *iface;   /* the §3.7.3 class string of the interface prototype object */
    const IdlUnscopableMember  *members;
    unsigned                    n;
} IdlUnscopablesRow;

static const IdlUnscopableMember IDL_UNSCOPABLE_CharacterData[] = {
    { "after",       IDL_GLOBAL_WINDOW },
    { "before",      IDL_GLOBAL_WINDOW },
    { "remove",      IDL_GLOBAL_WINDOW },
    { "replaceWith", IDL_GLOBAL_WINDOW },
};
static const IdlUnscopableMember IDL_UNSCOPABLE_Document[] = {
    { "append",          IDL_GLOBAL_WINDOW },
    { "fullscreen",      IDL_GLOBAL_WINDOW },
    { "prepend",         IDL_GLOBAL_WINDOW },
    { "replaceChildren", IDL_GLOBAL_WINDOW },
};
static const IdlUnscopableMember IDL_UNSCOPABLE_DocumentFragment[] = {
    { "append",          IDL_GLOBAL_WINDOW },
    { "prepend",         IDL_GLOBAL_WINDOW },
    { "replaceChildren", IDL_GLOBAL_WINDOW },
};
static const IdlUnscopableMember IDL_UNSCOPABLE_DocumentType[] = {
    { "after",       IDL_GLOBAL_WINDOW },
    { "before",      IDL_GLOBAL_WINDOW },
    { "remove",      IDL_GLOBAL_WINDOW },
    { "replaceWith", IDL_GLOBAL_WINDOW },
};
static const IdlUnscopableMember IDL_UNSCOPABLE_Element[] = {
    { "after",           IDL_GLOBAL_WINDOW },
    { "append",          IDL_GLOBAL_WINDOW },
    { "before",          IDL_GLOBAL_WINDOW },
    { "prepend",         IDL_GLOBAL_WINDOW },
    { "remove",          IDL_GLOBAL_WINDOW },
    { "replaceChildren", IDL_GLOBAL_WINDOW },
    { "replaceWith",     IDL_GLOBAL_WINDOW },
    { "slot",            IDL_GLOBAL_WINDOW },
};

static const IdlUnscopablesRow IDL_UNSCOPABLES[] = {
    { "CharacterData",    IDL_UNSCOPABLE_CharacterData, 4 },
    { "Document",         IDL_UNSCOPABLE_Document, 4 },
    { "DocumentFragment", IDL_UNSCOPABLE_DocumentFragment, 3 },
    { "DocumentType",     IDL_UNSCOPABLE_DocumentType, 4 },
    { "Element",          IDL_UNSCOPABLE_Element, 8 },
};

#endif
