/* GENERATED by engine/esglobalgen.mjs from engine/specindex/ecmascript.json — DO NOT EDIT.
 * Every global property name ECMAScript §19 The Global Object defines: the depth-2 subclauses of §19.1 Value
 * Properties of the Global Object, §19.2 Function Properties of the Global Object, §19.3 Constructor Properties
 * of the Global Object and §19.4 Other Properties of the Global Object. solver/absent.c reads this beside
 * browser/platform_names.h — the two vocabularies that own names on the global object — to tell a component
 * this engine OWES from server-injected app state.
 * Derived from: https://tc39.es/ecma262/multipage/
 * Corpus edition: Draft ECMA-262 / September 2, 2026
 * Not derived (fails the IdentifierName test, which is what a grouping heading does): §19.2.6 URI Handling Functions */
#ifndef APICLIENT_LANGUAGE_NAMES_H
#define APICLIENT_LANGUAGE_NAMES_H

static const char *const LANGUAGE_NAMES[] = {
    "AggregateError",
    "Array",
    "ArrayBuffer",
    "AsyncDisposableStack",
    "Atomics",
    "BigInt",
    "BigInt64Array",
    "BigUint64Array",
    "Boolean",
    "DataView",
    "Date",
    "DisposableStack",
    "Error",
    "EvalError",
    "FinalizationRegistry",
    "Float16Array",
    "Float32Array",
    "Float64Array",
    "Function",
    "Infinity",
    "Int16Array",
    "Int32Array",
    "Int8Array",
    "Iterator",
    "JSON",
    "Map",
    "Math",
    "NaN",
    "Number",
    "Object",
    "Promise",
    "Proxy",
    "RangeError",
    "ReferenceError",
    "Reflect",
    "RegExp",
    "Set",
    "SharedArrayBuffer",
    "String",
    "SuppressedError",
    "Symbol",
    "SyntaxError",
    "TypeError",
    "URIError",
    "Uint16Array",
    "Uint32Array",
    "Uint8Array",
    "Uint8ClampedArray",
    "WeakMap",
    "WeakRef",
    "WeakSet",
    "eval",
    "globalThis",
    "isFinite",
    "isNaN",
    "parseFloat",
    "parseInt",
    "undefined",
};

#endif
