/* GENERATED by engine/elemgen.mjs from the HTML Standard — DO NOT EDIT.
 * HTML §3.2.2 Elements in the DOM's "element interface", as ROWS: every local name the standard decides an
 * interface for in the HTML namespace, with the step of §3.2.2's seven that decided it. Steps 1-3 are the
 * three name lists §3.2.2 states itself; step 4's rows are HTML §4's element-interface index and the six
 * elements HTML §16.3 Requirements for implementations keeps an interface for.
 * The ALGORITHM is core/html/html_element.c's — including steps 5, 6 and 7, which decide names no row names.
 * The REFLECTIONS are html_element.c's too, joined onto these rows by interface name: a reflection is a
 * behaviour the index does not state, so generating one would be inventing it.
 * Regenerate with `node engine/elemgen.mjs --regen`, and commit the result — the build has no network and
 * this table is not optional. */
#ifndef APICLIENT_ELEMENT_INTERFACES_H
#define APICLIENT_ELEMENT_INTERFACES_H

/* X(local name, interface name, the §3.2.2 step that decided the row) */
#define HTML_ELEMENT_INTERFACES(X) \
    /* HTML §3.2.2 Elements in the DOM step 1 */ \
    X("applet", "HTMLUnknownElement", 1) \
    X("bgsound", "HTMLUnknownElement", 1) \
    X("blink", "HTMLUnknownElement", 1) \
    X("isindex", "HTMLUnknownElement", 1) \
    X("keygen", "HTMLUnknownElement", 1) \
    X("multicol", "HTMLUnknownElement", 1) \
    X("nextid", "HTMLUnknownElement", 1) \
    X("spacer", "HTMLUnknownElement", 1) \
    /* HTML §3.2.2 Elements in the DOM step 2 */ \
    X("acronym", "HTMLElement", 2) \
    X("basefont", "HTMLElement", 2) \
    X("big", "HTMLElement", 2) \
    X("center", "HTMLElement", 2) \
    X("nobr", "HTMLElement", 2) \
    X("noembed", "HTMLElement", 2) \
    X("noframes", "HTMLElement", 2) \
    X("plaintext", "HTMLElement", 2) \
    X("rb", "HTMLElement", 2) \
    X("rtc", "HTMLElement", 2) \
    X("strike", "HTMLElement", 2) \
    X("tt", "HTMLElement", 2) \
    /* HTML §3.2.2 Elements in the DOM step 3 */ \
    X("listing", "HTMLPreElement", 3) \
    X("xmp", "HTMLPreElement", 3) \
    /* HTML §3.2.2 step 4 — HTML §4's element-interface index */ \
    X("a", "HTMLAnchorElement", 4) \
    X("abbr", "HTMLElement", 4) \
    X("address", "HTMLElement", 4) \
    X("area", "HTMLAreaElement", 4) \
    X("article", "HTMLElement", 4) \
    X("aside", "HTMLElement", 4) \
    X("audio", "HTMLAudioElement", 4) \
    X("b", "HTMLElement", 4) \
    X("base", "HTMLBaseElement", 4) \
    X("bdi", "HTMLElement", 4) \
    X("bdo", "HTMLElement", 4) \
    X("blockquote", "HTMLQuoteElement", 4) \
    X("body", "HTMLBodyElement", 4) \
    X("br", "HTMLBRElement", 4) \
    X("button", "HTMLButtonElement", 4) \
    X("canvas", "HTMLCanvasElement", 4) \
    X("caption", "HTMLTableCaptionElement", 4) \
    X("cite", "HTMLElement", 4) \
    X("code", "HTMLElement", 4) \
    X("col", "HTMLTableColElement", 4) \
    X("colgroup", "HTMLTableColElement", 4) \
    X("data", "HTMLDataElement", 4) \
    X("datalist", "HTMLDataListElement", 4) \
    X("dd", "HTMLElement", 4) \
    X("del", "HTMLModElement", 4) \
    X("details", "HTMLDetailsElement", 4) \
    X("dfn", "HTMLElement", 4) \
    X("dialog", "HTMLDialogElement", 4) \
    X("div", "HTMLDivElement", 4) \
    X("dl", "HTMLDListElement", 4) \
    X("dt", "HTMLElement", 4) \
    X("em", "HTMLElement", 4) \
    X("embed", "HTMLEmbedElement", 4) \
    X("fieldset", "HTMLFieldSetElement", 4) \
    X("figcaption", "HTMLElement", 4) \
    X("figure", "HTMLElement", 4) \
    X("footer", "HTMLElement", 4) \
    X("form", "HTMLFormElement", 4) \
    X("h1", "HTMLHeadingElement", 4) \
    X("h2", "HTMLHeadingElement", 4) \
    X("h3", "HTMLHeadingElement", 4) \
    X("h4", "HTMLHeadingElement", 4) \
    X("h5", "HTMLHeadingElement", 4) \
    X("h6", "HTMLHeadingElement", 4) \
    X("head", "HTMLHeadElement", 4) \
    X("header", "HTMLElement", 4) \
    X("hgroup", "HTMLElement", 4) \
    X("hr", "HTMLHRElement", 4) \
    X("html", "HTMLHtmlElement", 4) \
    X("i", "HTMLElement", 4) \
    X("iframe", "HTMLIFrameElement", 4) \
    X("img", "HTMLImageElement", 4) \
    X("input", "HTMLInputElement", 4) \
    X("ins", "HTMLModElement", 4) \
    X("kbd", "HTMLElement", 4) \
    X("label", "HTMLLabelElement", 4) \
    X("legend", "HTMLLegendElement", 4) \
    X("li", "HTMLLIElement", 4) \
    X("link", "HTMLLinkElement", 4) \
    X("main", "HTMLElement", 4) \
    X("map", "HTMLMapElement", 4) \
    X("mark", "HTMLElement", 4) \
    X("menu", "HTMLMenuElement", 4) \
    X("meta", "HTMLMetaElement", 4) \
    X("meter", "HTMLMeterElement", 4) \
    X("nav", "HTMLElement", 4) \
    X("noscript", "HTMLElement", 4) \
    X("object", "HTMLObjectElement", 4) \
    X("ol", "HTMLOListElement", 4) \
    X("optgroup", "HTMLOptGroupElement", 4) \
    X("option", "HTMLOptionElement", 4) \
    X("output", "HTMLOutputElement", 4) \
    X("p", "HTMLParagraphElement", 4) \
    X("picture", "HTMLPictureElement", 4) \
    X("pre", "HTMLPreElement", 4) \
    X("progress", "HTMLProgressElement", 4) \
    X("q", "HTMLQuoteElement", 4) \
    X("rp", "HTMLElement", 4) \
    X("rt", "HTMLElement", 4) \
    X("ruby", "HTMLElement", 4) \
    X("s", "HTMLElement", 4) \
    X("samp", "HTMLElement", 4) \
    X("search", "HTMLElement", 4) \
    X("script", "HTMLScriptElement", 4) \
    X("section", "HTMLElement", 4) \
    X("select", "HTMLSelectElement", 4) \
    X("selectedcontent", "HTMLSelectedContentElement", 4) \
    X("slot", "HTMLSlotElement", 4) \
    X("small", "HTMLElement", 4) \
    X("source", "HTMLSourceElement", 4) \
    X("span", "HTMLSpanElement", 4) \
    X("strong", "HTMLElement", 4) \
    X("style", "HTMLStyleElement", 4) \
    X("sub", "HTMLElement", 4) \
    X("summary", "HTMLElement", 4) \
    X("sup", "HTMLElement", 4) \
    X("table", "HTMLTableElement", 4) \
    X("tbody", "HTMLTableSectionElement", 4) \
    X("td", "HTMLTableCellElement", 4) \
    X("template", "HTMLTemplateElement", 4) \
    X("textarea", "HTMLTextAreaElement", 4) \
    X("tfoot", "HTMLTableSectionElement", 4) \
    X("th", "HTMLTableCellElement", 4) \
    X("thead", "HTMLTableSectionElement", 4) \
    X("time", "HTMLTimeElement", 4) \
    X("title", "HTMLTitleElement", 4) \
    X("tr", "HTMLTableRowElement", 4) \
    X("track", "HTMLTrackElement", 4) \
    X("u", "HTMLElement", 4) \
    X("ul", "HTMLUListElement", 4) \
    X("var", "HTMLElement", 4) \
    X("video", "HTMLVideoElement", 4) \
    X("wbr", "HTMLElement", 4) \
    /* HTML §3.2.2 step 4 — HTML §16.3 Requirements for implementations */ \
    X("marquee", "HTMLMarqueeElement", 4) \
    X("frameset", "HTMLFrameSetElement", 4) \
    X("frame", "HTMLFrameElement", 4) \
    X("dir", "HTMLDirectoryElement", 4) \
    X("font", "HTMLFontElement", 4) \
    X("param", "HTMLParamElement", 4)

#endif
