/* CSSOM VIEW §7 — EXTENSIONS TO THE HTMLElement INTERFACE, the OFFSET family: how a page asks how big a box is
 * and where it sits, and the members whose absence was SILENT rather than loud.
 *
 * WHY THIS SECTION IS ITS OWN COMPONENT AND NOT A BLOCK INSIDE core/dom/element_view.c. §6 is a `partial
 * interface Element` and §7 is a `partial interface HTMLElement`, and that is not a filing detail: `svg.offsetTop`
 * is `undefined` in every user agent and `svg.clientTop` is 0, because the two sections install on two
 * prototypes. A member of this section reached through `.call` on a non-HTML element is a TypeError, which is
 * WEB IDL §3.7.6 Attributes' brand check over HTMLElement rather than over Element, and one file installing
 * both could
 * not state that. The DERIVATIONS the two share — the has-a-box predicate, the `long` conversion and its mint,
 * the fragment count — are stated ONCE in core/dom/element_view.h and read from here.
 *
 * THE ABSENCE THIS FILE ENDS WAS INVISIBLE, WHICH IS WHY IT OUTLASTED LOUDER ONES. quickjs's missing-property
 * hook fires for a GLOBAL receiver only, so `el.offsetWidth` on an element that had no such member was a plain
 * `undefined` — no throw, no crash, nothing for a forced-exec flow to park on. A real bundle's
 * `t.offsetWidth && (s = l.width / t.offsetWidth)` then took its false arm every time and the scale stayed 1,
 * so a whole branch of a real site was never explored and NOTHING said so. That is §Consumer-defaults' shape
 * one layer out: a plausible datum indistinguishable from a measurement, produced by a producer that does not
 * exist. The members below compute REAL values from the layout this engine has, and crash where it does not.
 *
 * WHAT §7 ASKS FOR, AND WHY THE TWO HALVES ANSWER DIFFERENTLY. core/dom/element_view.h states the split every
 * CSSOM VIEW member falls on — an EXTENT is a distance between two parallel edges of ONE box and
 * core/layout/used_value.h computes it; a POSITION is a coordinate in another box's space and
 * core/layout/flow_position.h places it — and §7 lands on both sides at once:
 *   - `offsetWidth`/`offsetHeight` are EXTENTS. Step 2 is "the unscaled width of the axis-aligned bounding box
 *     of the border boxes of all fragments generated by the element's principal box", and for a box that
 *     generates ONE fragment that bounding box IS that fragment's border box —
 *     `used_value_border_edge_px`, whose own header names these two members as its second caller. They are
 *     answered for every box CSS 2.1 §10 sizes, which is the vue.js read above.
 *   - `offsetTop`/`offsetLeft` are POSITIONS, and they are DIFFERENCES of two of them: step 3 subtracts the
 *     offsetParent's top padding edge from the element's own top border edge, both "relative to the initial
 *     containing block origin" — which is exactly the space core/layout/flow_position.h answers in, so the
 *     subtraction needs no frame conversion at all (§6's client rectangles need one; these do not).
 *   - `offsetParent` is NEITHER. It is a walk over the TREE and over computed values, with no geometry in it,
 *     which is why it is the member of this section that is answered in full for every element this engine can
 *     lay out — and it has to be, because the two above are DEFINED against it.
 *
 * STEP 1 IS A REAL ZERO AND IT IS TOLD APART FROM AN ABSENT NUMBER BY WHERE IT IS WRITTEN. Every member here
 * opens with §7's own "return zero" for an element with no associated box, and `offsetTop`/`offsetLeft` add the
 * BODY ELEMENT to it. That zero is what every user agent reports, for a reason that has nothing to do with this
 * engine's layout: an element that generates no box has no border box to measure and no position to be at. So
 * it is a COMPUTED VALUE, it is CONCRETE (core/frame/viewport.h's test: a domain of one point has no arm to
 * explore), and it is written as the spec's own first step rather than as a fallback at the end — the only
 * place in this file a zero appears is where §7 puts one. Everything past step 1 either computes a number or
 * CRASHES naming the section it is waiting on.
 *
 * WHAT THIS ENGINE CANNOT READ, AND HOW EVERY MEMBER HERE FINDS OUT. §7's walk branches on facts that come from
 * properties core/css/css_computed_value.h does not model, and there are exactly two SOURCES of them:
 *   - css-position-3 §2.1 "Containing Blocks of Positioned Boxes" names what makes a box establish an absolute
 *     or a fixed positioning containing block, and its own Note is an OPEN LIST: "Properties that can cause a
 *     box to establish an absolute positioning containing block include position, transform, will-change,
 *     contain …". `position` is modelled here; the rest are not.
 *   - CSS Viewport §4 "The zoom property": "the effective zoom of an element is the product of its computed
 *     value of zoom and all flat tree ancestors' computed values of zoom", and "the unscaled value of a CSS
 *     length relative to an element is the scaled value divided by the element's effective zoom". Every extent
 *     and every coordinate §7 reports is an UNSCALED one, and `zoom` is not modelled either.
 *   So the ancestor chain is checked for a DECLARATION of one of those properties before any of them is read,
 *   and a declaration CRASHES naming the computed-value rule to build. With none declared the derivations are
 *   exact rather than approximate: no element establishes a fixed positioning containing block, an element
 *   establishes an absolute one exactly when its computed `position` is not `static`, and every effective zoom
 *   is 1 so every used value in CSS pixels is already the unscaled value. Reading the CASCADED value to decide
 *   whether to crash is not the specified-value-under-the-word-computed that css_computed_value.h forbids: it
 *   is a DETECTOR for an input this component cannot read, and its only outcome is the crash.
 *
 * BUT WHICH MEMBER EACH OF THOSE PROPERTIES IS AN OPERAND OF IS TWO QUESTIONS, AND ASKING THEM AS ONE COST THE
 * EXTENTS. A single list of the four gated all five members alike, so an ancestor declaring `transform` aborted
 * `offsetHeight` — CLAUDE.md's two-question predicate, where the STRICTER question decides and the LOOSER one
 * pays a cost that reads as correctness. §2.1's own opening sentence is what separates them, and it is a SCOPE
 * statement: "The containing block of a static, relative, or sticky box is as defined by its formatting
 * context. For fixed and absolute boxes, it is defined as follows". So `transform` and `will-change` — whose
 * only other effects are a stacking context and the same containing blocks, per css-transforms-1 §2 "The
 * Transform Rendering Model" and css-will-change-1 §2 "Hinting at Future Behavior: the will-change property" —
 * reach a used value ONLY where some box on the chain is `absolute` or `fixed`. `contain` and `zoom` do not
 * split that way and stay unconditional: css-contain-2 §3.1 "Size Containment" makes `contain` a fact about a
 * box's own intrinsic sizes rather than about anyone's containing block, and every number §7 reports is
 * unscaled. §7's own text is the third witness for the members that matter: an extent is returned "ignoring any
 * transforms that apply to the element and its ancestors". The consequence is the ordinary infinite-scroll
 * read: `el.offsetHeight` under a transformed or will-changed ancestor now answers instead of aborting the
 * document, wherever nothing on the chain is absolutely or fixed positioned.
 *
 * AND THE FLAT TREE IS THE THIRD, ANSWERED THE SAME WAY. §7's walk is over "the parent of the element in the
 * flat tree" — CSS Scoping §4.1 "Flattening the DOM into an Element Tree" — and its second clause is DOM §4.8's
 * "closed-shadow-hidden". Neither exists in this engine: there is no flat-tree parent and no slot assignment to
 * read one from. The node tree IS the flat tree for an element whose root is not a shadow root and none of
 * whose ancestors hosts one, which is a checkable condition and is checked; anything else crashes naming both
 * definitions. A silent node-tree walk would answer a slotted element's offsetParent with an ancestor the flat
 * tree does not have it under, which is a wrong element rather than an absent one.
 *
 * NOTHING HERE IS STORED. Every answer is derived per read from the running flow's own tree and its own
 * cascade, which is core/layout/used_value.h's decision for its reason: a box tree cached across a context
 * switch is exactly the shared state the COW delta does not swap, and a derivation is per-flow by construction.
 *
 * WHAT IS HONESTLY ABSENT: `scrollParent`, §7's sixth member. Its step 2 returns "the scrollingElement for the
 * element's document" when the walk reaches the initial containing block, and `scrollingElement` is CSSOM VIEW
 * §5's member on Document — it does not exist in this engine (nothing in the tree defines or reads that name),
 * so the walk's terminating case has nothing to answer with. Its other two operands DO exist: the containing
 * block chain is core/layout/used_value.h's `used_value_containing_block`, and css-overflow-3 §3's SCROLL
 * CONTAINER is the computed `overflow-x`/`overflow-y` core/css/css_computed_value.h already derives. BUILD §5's
 * `scrollingElement` first; this member is then that walk over the two components that already answer. The IDL
 * audit reports it, which is correct. */
#ifndef ENGINE_HOST_BROWSER_CORE_HTML_HTML_ELEMENT_VIEW_H
#define ENGINE_HOST_BROWSER_CORE_HTML_HTML_ELEMENT_VIEW_H

#include "quickjs.h"

/* CSSOM VIEW §7 "Extensions to the HTMLElement Interface"'s `partial interface HTMLElement`, for ONE realm —
   installed on the prototype html_element.c has just built, beside every other member of it. It is per realm
   because its answers are: a child navigable's initial containing block is 300 CSS pixels wide and the
   top-level traversable's is 1280, every used value below
   bottoms out in one of them, and a C member runs in the realm that DEFINED it.
   THERE IS NO `_init` BESIDE IT, and that is a statement rather than an omission: §7 declares six readonly
   attributes and no operation and no setter, so there is nothing to declare once per agent — the accessor
   install carries the whole member. */
void html_element_view_install(JSContext *ctx, JSValueConst proto);

#endif
